// TBook Control State Machine   tbook_csm_def.h
// generated by CSMcompile version: 6, 2021-05-20 add filesTest action & events
// run at 2021-09-23 15:05:51
// from C:\Users\geneb\Documents\CSMcompile\data\control_def.txt of: 2021-09-23 15:05:46
#include "controlmanager.h" 
char CSM_Version[] = "PRE: // TB CSM 2021-09-23: V11 QC test-- skip on Star after Home"; 
TBConfig_t  TB_Config = { 
  6,  // default_volume 
  300000,  // powerCheckMS 
  5000,  // shortIdleMS 
  20000,  // longIdleMS 
  50,  // minShortPressMS 
  1000,  // minLongPressMS 
  0, // qcTestState 
  1, // initState 
  "system/audio/",  // systemAudio 
  "_49G",  // bgPulse 
  "G!",  // fgPlaying 
  "G2_3!",  // fgPlayPaused 
  "R!",  // fgRecording 
  "R2_3!",  // fgRecordPaused 
  "O!",  // fgSavingRec 
  "G3_3G3",  // fgSaveRec 
  "R3_3R3",  // fgCancelRec 
  "O5o5!",  // fgUSB_MSC 
  "R8_2R8_2R8_20!",  // fgTB_Error 
  "_3R3_3R3_3R3_5!",  // fgNoUSBcable 
  "G5g5!",  // fgUSBconnect 
  "G_3G_3G_9G_3G_9G_3",  // fgPowerDown 
}; 
int   nPlaySys = 7;  // # PlaySys prompts used by CSM 
SysAudio_t SysAudio[] = { 
{ "welcome",  "M0:/system/audio/welcome.wav" }, 
{ "rh_for_subj",  "M0:/system/audio/rh_for_subj.wav" }, 
{ "rh_for_nxt_subj",  "M0:/system/audio/rh_for_nxt_subj.wav" }, 
{ "cir_record_ideas",  "M0:/system/audio/cir_record_ideas.wav" }, 
{ "rh_things_to_do",  "M0:/system/audio/rh_things_to_do.wav" }, 
{ "louder",  "M0:/system/audio/louder.wav" }, 
{ "softer",  "M0:/system/audio/softer.wav" }, 
};  // SysAudio 
int   nCSMstates = 78;  // TBook state machine definition 
csmState stQcTest =  // TBookCMS[0] 
  {  0, "stQcTest", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     {  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 47,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, },
     1, {  
          { playTune, "C." },
        }
  }; 
csmState stWakeup =  // TBookCMS[1] 
  {  1, "stWakeup", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     {  1,  1,  1,  4,  5, 12, 10, 11,  6,  1, 13,  2,  1,  1,  1,  1,  7,  8,  1,  1,  1,  1, 15,  1,  1,  1,  1,  1,  1,  1,  1, 34, 14, 14,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, },
     4, {  
          { LED, "_" },
          { bgLED, "bgPulse" },
          { changePkg, "" },
          { playSys, "welcome" },
        }
  }; 
csmState stSleepy =  // TBookCMS[2] 
  {  2, "stSleepy", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     {  2,  1, 37, 37, 37, 37, 37, 37, 37, 37, 37,  2,  1, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,  2,  2,  2,  2,  2,  2,  2,  2, 38,  2,  2,  2,  2,  2, },
     3, {  
          { bgLED, "O_9" },
          { saveSt, "1" },
          { setTimer, "5000" },
        }
  }; 
csmState stCloseUSB =  // TBookCMS[3] 
  {  3, "stCloseUSB", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     {  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  1,  3,  3,  3,  3,  3, },
     3, {  
          { endUSB, "" },
          { bgLED, "G_29" },
          { setTimer, "1000" },
        }
  }; 
csmState stPlayLouder =  // TBookCMS[4] 
  {  4, "stPlayLouder", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     {  4,  1,  4,  4,  5,  4,  4,  4,  6,  4,  4,  2,  1,  4,  4,  4,  7,  8,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  2,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4, },
     2, {  
          { volAdj, "1" },
          { goPrevSt, "" },
        }
  }; 
csmState stPlaySofter =  // TBookCMS[5] 
  {  5, "stPlaySofter", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     {  5,  1,  5,  4,  5,  5,  5,  5,  6,  5,  5,  2,  1,  5,  5,  5,  7,  8,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  2,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5, },
     2, {  
          { volAdj, "-1" },
          { goPrevSt, "" },
        }
  }; 
csmState stPlayPause =  // TBookCMS[6] 
  {  6, "stPlayPause", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     {  6,  1,  6,  4,  5, 12, 10, 11,  9,  6, 13,  2,  1,  6,  6,  6,  7,  8,  6,  6,  6,  6, 15,  6,  6,  6,  6,  6,  6,  6,  6,  6, 14, 14,  2,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6, },
     2, {  
          { saveSt, "2" },
          { pausePlay, "" },
        }
  }; 
csmState stPlayJumpBack =  // TBookCMS[7] 
  {  7, "stPlayJumpBack", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     {  7,  1,  7,  4,  5, 12, 10, 11,  6,  7, 13,  2,  1,  7,  7,  7,  7,  8,  7,  7,  7,  7, 15,  7,  7,  7,  7,  7,  7,  7,  7,  7, 14, 14,  2,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7, },
     1, {  
          { posAdj, "-7" },
        }
  }; 
csmState stPlayJumpFwd =  // TBookCMS[8] 
  {  8, "stPlayJumpFwd", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     {  8,  1,  8,  4,  5, 12, 10, 11,  6,  8, 13,  2,  1,  8,  8,  8,  7,  8,  8,  8,  8,  8, 15,  8,  8,  8,  8,  8,  8,  8,  8,  8, 14, 14,  2,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8, },
     1, {  
          { posAdj, "60" },
        }
  }; 
csmState stPlayResume =  // TBookCMS[9] 
  {  9, "stPlayResume", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     {  9,  1,  9,  4,  5, 12, 10, 11,  6,  9, 13,  2,  1,  9,  9,  9,  7,  8,  9,  9,  9,  9, 15,  9,  9,  9,  9,  9,  9,  9,  9,  9, 14, 14,  2,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, },
     2, {  
          { resumePlay, "" },
          { goSavedSt, "2" },
        }
  }; 
csmState stOnPrevSubj =  // TBookCMS[10] 
  {  10, "stOnPrevSubj", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 10,  1, 10,  4,  5, 12, 10, 11,  6, 10, 13,  2,  1, 10, 10, 10,  7,  8, 10, 10, 10, 10, 15, 10, 10, 10, 10, 10, 10, 10, 10, 40, 14, 14,  2, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, },
     2, {  
          { subjAdj, "-1" },
          { playSubj, "nm" },
        }
  }; 
csmState stOnNextSubj =  // TBookCMS[11] 
  {  11, "stOnNextSubj", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 11,  1, 11,  4,  5, 12, 10, 11,  6, 11, 13,  2,  1, 11, 11, 11,  7,  8, 11, 11, 11, 11, 15, 11, 11, 11, 11, 11, 11, 11, 11, 40, 14, 14,  2, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, },
     2, {  
          { subjAdj, "1" },
          { playSubj, "nm" },
        }
  }; 
csmState stOnNextMsg =  // TBookCMS[12] 
  {  12, "stOnNextMsg", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 12,  1, 12,  4,  5, 12, 10, 11,  6, 12, 13,  2,  1, 12, 12, 12,  7,  8, 12, 12, 12, 12, 15, 12, 12, 12, 12, 12, 12, 12, 12, 43, 14, 14,  2, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, },
     2, {  
          { msgAdj, "1" },
          { playSubj, "msg" },
        }
  }; 
csmState stOnPrevMsg =  // TBookCMS[13] 
  {  13, "stOnPrevMsg", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 13,  1, 13,  4,  5, 12, 10, 11,  6, 13, 13,  2,  1, 13, 13, 13,  7,  8, 13, 13, 13, 13, 15, 13, 13, 13, 13, 13, 13, 13, 13, 43, 14, 14,  2, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, },
     2, {  
          { msgAdj, "-1" },
          { playSubj, "msg" },
        }
  }; 
csmState stWait =  // TBookCMS[14] 
  {  14, "stWait", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 14,  1, 14, 25, 26, 12, 10, 11, 14, 14, 13,  2,  1, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 24, 28, 14, 14, 30, 29, 14, 27, 14, 14, 14,  2, 23, 14, 14, 14, 14, 14, 14, 14, 14, 14, },
    0
  }; 
csmState stOnFeedback =  // TBookCMS[15] 
  {  15, "stOnFeedback", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 15,  1, 17, 15, 15, 15, 15, 15, 15, 16, 15,  2,  1, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,  2, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, },
     1, {  
          { playSys, "cir_record_ideas" },
        }
  }; 
csmState stFbOptions =  // TBookCMS[16] 
  {  16, "stFbOptions", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 16,  1, 16, 16, 16, 16, 16, 16, 16, 16, 16,  2,  1, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,  2, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, },
     1, {  
          { playSys, "rh_things_to_do" },
        }
  }; 
csmState stStartRec =  // TBookCMS[17] 
  {  17, "stStartRec", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 17,  1, 19, 17, 17, 20, 17, 17, 18, 22, 21,  2,  1, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,  2, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, },
     1, {  
          { startRec, "" },
        }
  }; 
csmState stPauseRec =  // TBookCMS[18] 
  {  18, "stPauseRec", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 18,  1, 19, 18, 18, 20, 18, 18, 18, 22, 21,  2,  1, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,  2, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, },
     2, {  
          { saveSt, "2" },
          { pauseRec, "" },
        }
  }; 
csmState stFinishRec =  // TBookCMS[19] 
  {  19, "stFinishRec", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 19,  1, 19, 19, 19, 20, 19, 19, 18, 22, 21,  2,  1, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,  2, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, },
     1, {  
          { finishRec, "" },
        }
  }; 
csmState stPlayRec =  // TBookCMS[20] 
  {  20, "stPlayRec", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 20,  1, 19, 20, 20, 20, 20, 20, 18, 22, 21,  2,  1, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,  2, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, },
     1, {  
          { playRec, "" },
        }
  }; 
csmState stCancelRec =  // TBookCMS[21] 
  {  21, "stCancelRec", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 21,  1, 21, 21, 21, 12, 10, 11, 21, 21, 13,  2,  1, 21, 21, 21, 21, 21, 21, 21, 21, 21, 15, 21, 21, 21, 21, 21, 21, 21, 21, 21, 14, 14,  2, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, },
     1, {  
          { saveRec, "del" },
        }
  }; 
csmState stSaveRec =  // TBookCMS[22] 
  {  22, "stSaveRec", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 22,  1, 22, 22, 22, 12, 10, 11, 22, 22, 13,  2,  1, 22, 22, 22, 22, 22, 22, 22, 22, 22, 15, 22, 22, 22, 22, 22, 22, 22, 22, 22, 14, 14,  2, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, },
     1, {  
          { saveRec, "sv" },
        }
  }; 
csmState stLowBatt =  // TBookCMS[23] 
  {  23, "stLowBatt", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 23,  1, 23, 25, 26, 23, 23, 23, 23, 23, 23,  2,  1, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 28, 23, 23, 30, 29, 23, 27, 23, 23, 23,  2, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, },
    0
  }; 
csmState stUSBmode =  // TBookCMS[24] 
  {  24, "stUSBmode", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24,  3, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, 24, },
     2, {  
          { bgLED, "O2_8" },
          { startUSB, "" },
        }
  }; 
csmState stIdleLouder =  // TBookCMS[25] 
  {  25, "stIdleLouder", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 25,  1, 25,  4,  5, 25, 25, 25,  6, 25, 25,  2,  1, 25, 25, 25,  7,  8, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,  2, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, },
     3, {  
          { volAdj, "1" },
          { playSys, "louder" },
          { goPrevSt, "" },
        }
  }; 
csmState stIdleSofter =  // TBookCMS[26] 
  {  26, "stIdleSofter", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 26,  1, 26,  4,  5, 26, 26, 26,  6, 26, 26,  2,  1, 26, 26, 26,  7,  8, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26,  2, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, },
     3, {  
          { volAdj, "-1" },
          { playSys, "softer" },
          { goPrevSt, "" },
        }
  }; 
csmState stTest =  // TBookCMS[27] 
  {  27, "stTest", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 27,  1, 27, 27, 27, 27, 27, 27, 27, 27, 27,  2,  1, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,  2, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, },
     1, {  
          { sysTest, "" },
        }
  }; 
csmState stOnUpdate =  // TBookCMS[28] 
  {  28, "stOnUpdate", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 28,  1, 28, 28, 28, 28, 28, 28, 28, 28, 28,  2,  1, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28,  2, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, },
     1, {  
          { sysBoot, "" },
        }
  }; 
csmState stNxtPkg =  // TBookCMS[29] 
  {  29, "stNxtPkg", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 29,  1, 29, 25, 26, 29, 29, 29, 29, 29, 29,  2,  1, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 24, 28, 29, 29, 30, 29, 29, 27, 29, 29, 29,  2, 23, 29, 29, 29, 29, 29, 29, 29, 29, 29, },
     1, {  
          { playNxtPkg, "" },
        }
  }; 
csmState stChgPkg =  // TBookCMS[30] 
  {  30, "stChgPkg", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 30,  1, 30, 25, 26, 12, 10, 11, 30, 30, 13,  2,  1, 30, 30, 30, 30, 30, 30, 30, 30, 30, 15, 24, 28, 30, 30, 30, 29, 30, 27, 30, 14, 14,  2, 23, 30, 30, 30, 30, 30, 30, 30, 30, 30, },
     1, {  
          { changePkg, "" },
        }
  }; 
csmState stQcUSB =  // TBookCMS[31] 
  {  31, "stQcUSB", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 31, 32, 31, 31, 31, 31, 31, 31, 33, 31,  0, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, },
     2, {  
          { bgLED, "O2_8" },
          { startUSB, "" },
        }
  }; 
csmState stQcReboot =  // TBookCMS[32] 
  {  32, "stQcReboot", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, },
     1, {  
          { sysBoot, "" },
        }
  }; 
csmState stQcSysTest =  // TBookCMS[33] 
  {  33, "stQcSysTest", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 33, 32, 33, 33, 33, 33, 33, 33, 33, 31,  0, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, },
     1, {  
          { playTune, "CG..FDEH.G." },
        }
  }; 
csmState stWelcoming =  // TBookCMS[34] 
  {  34, "stWelcoming", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 34,  1, 34,  4,  5, 12, 10, 11,  6, 34, 13,  2,  1, 34, 34, 34,  7,  8, 34, 34, 34, 34, 15, 34, 34, 34, 34, 34, 34, 34, 34, 34, 35, 14,  2, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, },
    0
  }; 
csmState stPromptSubj =  // TBookCMS[35] 
  {  35, "stPromptSubj", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 35,  1, 35,  4,  5, 12, 10, 11,  6, 35, 13,  2,  1, 35, 35, 35,  7,  8, 35, 35, 35, 35, 15, 35, 35, 35, 35, 35, 35, 35, 35, 36, 14, 14,  2, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, },
     1, {  
          { playSys, "rh_for_subj" },
        }
  }; 
csmState stPromptingSub =  // TBookCMS[36] 
  {  36, "stPromptingSub", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 36,  1, 36,  4,  5, 12, 10, 11,  6, 36, 13,  2,  1, 36, 36, 36,  7,  8, 36, 36, 36, 36, 15, 36, 36, 36, 36, 36, 36, 36, 36, 36, 14, 14,  2, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, },
    0
  }; 
csmState stUnSleepy =  // TBookCMS[37] 
  {  37, "stUnSleepy", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 37,  1, 37, 37, 37, 37, 37, 37, 37, 37, 37,  2,  1, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,  2, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, },
     2, {  
          { bgLED, "bgPulse" },
          { goSavedSt, "1" },
        }
  }; 
csmState stGoSleep =  // TBookCMS[38] 
  {  38, "stGoSleep", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 38,  1,  1, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 39, 38, 38, 38, 38, 38, },
     2, {  
          { bgLED, "R_3" },
          { setTimer, "1000" },
        }
  }; 
csmState stFallAsleep =  // TBookCMS[39] 
  {  39, "stFallAsleep", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 39,  1,  1, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, 39, },
     1, {  
          { powerDown, "" },
        }
  }; 
csmState stAnnouncing =  // TBookCMS[40] 
  {  40, "stAnnouncing", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 40,  1, 40,  4,  5, 12, 10, 11,  6, 40, 13,  2,  1, 40, 40, 40,  7,  8, 40, 40, 40, 40, 15, 40, 40, 40, 40, 40, 40, 40, 40, 40, 41, 14,  2, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, },
    0
  }; 
csmState stInvitation =  // TBookCMS[41] 
  {  41, "stInvitation", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 41,  1, 41,  4,  5, 12, 10, 11,  6, 41, 13,  2,  1, 41, 41, 41,  7,  8, 41, 41, 41, 41, 15, 41, 41, 41, 41, 41, 41, 41, 41, 41, 42, 14,  2, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, },
     1, {  
          { playSubj, "pr" },
        }
  }; 
csmState stPromptNextSubj =  // TBookCMS[42] 
  {  42, "stPromptNextSubj", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 42,  1, 42,  4,  5, 12, 10, 11,  6, 42, 13,  2,  1, 42, 42, 42,  7,  8, 42, 42, 42, 42, 15, 42, 42, 42, 42, 42, 42, 42, 42, 42, 14, 14,  2, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, },
     1, {  
          { playSys, "rh_for_nxt_subj" },
        }
  }; 
csmState stPlaying =  // TBookCMS[43] 
  {  43, "stPlaying", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 43,  1, 43,  4,  5, 12, 10, 11,  6, 43, 13,  2,  1, 43, 43, 43,  7,  8, 43, 43, 43, 43, 15, 43, 43, 43, 43, 43, 43, 43, 43, 43, 14, 14,  2, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, },
    0
  }; 
csmState stOnLowBatt =  // TBookCMS[44] 
  {  44, "stOnLowBatt", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 44,  1, 44, 44, 44, 44, 44, 44, 44, 44, 44,  2,  1, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44,  2, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, },
     1, {  
          { bgLED, "R_9" },
        }
  }; 
csmState stOnCharging =  // TBookCMS[45] 
  {  45, "stOnCharging", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 45,  1, 45, 25, 26, 45, 45, 45, 45, 45, 45,  2,  1, 45, 45, 45, 45, 45, 45, 45, 45, 45, 45, 24, 28, 45, 45, 30, 29, 45, 27, 45, 45, 45,  2, 23, 45, 45, 45, 45, 45, 45, 45, 45, 45, },
     2, {  
          { showCharge, "" },
          { goPrevSt, "" },
        }
  }; 
csmState stGoFWU =  // TBookCMS[46] 
  {  46, "stGoFWU", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 46,  1, 46, 46, 46, 46, 46, 46, 46, 46, 46,  2,  1, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46,  2, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46, },
    0
  }; 
csmState stQc1 =  // TBookCMS[47] 
  {  47, "stQc1", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 47, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 47, 48, 49, },
     2, {  
          { filesTest, "" },
          { bgLED, "G3_3" },
        }
  }; 
csmState stQc2 =  // TBookCMS[48] 
  {  48, "stQc2", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 48, 50, 50, 51, 50, 50, 50, 50, 50, 50, 52, 50, 50, 51, 50, 50, 50, 50, 50, 50, 52, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, 48, },
     2, {  
          { bgLED, "G3_3" },
          { playTune, "G." },
        }
  }; 
csmState stQcErrFiles =  // TBookCMS[49] 
  {  49, "stQcErrFiles", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 49, 32, 49, 49, 49, 49, 49, 49, 33, 31,  0, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, 49, },
     3, {  
          { writeMsg, "filesTest" },
          { bgLED, "R9_6" },
          { playTune, "H.*_H.*_H.*_H.*_" },
        }
  }; 
csmState stQcBeep =  // TBookCMS[50] 
  {  50, "stQcBeep", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, },
     2, {  
          { playTune, "H_H" },
          { goPrevSt, "" },
        }
  }; 
csmState stQc3 =  // TBookCMS[51] 
  {  51, "stQc3", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 51, 53, 50, 50, 50, 50, 50, 50, 50, 50, 54, 53, 50, 50, 50, 50, 50, 50, 50, 50, 54, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, 51, },
     2, {  
          { bgLED, "R3_3" },
          { playTune, "E." },
        }
  }; 
csmState stQcErrGrn =  // TBookCMS[52] 
  {  52, "stQcErrGrn", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 52, 32, 52, 52, 52, 52, 52, 52, 33, 31,  0, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, },
     3, {  
          { writeMsg, "no_Green" },
          { bgLED, "R9_6" },
          { playTune, "H.*_H.*_H.*_H.*_" },
        }
  }; 
csmState stQc4 =  // TBookCMS[53] 
  {  53, "stQc4", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 53, 50, 50, 50, 55, 50, 50, 50, 50, 57, 56, 50, 50, 50, 55, 50, 50, 50, 50, 57, 56, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, 53, },
     3, {  
          { bgLED, "_" },
          { LED, "G3" },
          { playTune, "C." },
        }
  }; 
csmState stQcErrRed =  // TBookCMS[54] 
  {  54, "stQcErrRed", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 54, 32, 54, 54, 54, 54, 54, 54, 33, 31,  0, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, 54, },
     3, {  
          { writeMsg, "no_Red" },
          { bgLED, "R9_6" },
          { playTune, "H.*_H.*_H.*_H.*_" },
        }
  }; 
csmState stQc5 =  // TBookCMS[55] 
  {  55, "stQc5", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 55, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 55, 55, 55, 55, 55, 55, 55, 55, 58, 55, 55, 55, 55, 55, },
     2, {  
          { startRec, "" },
          { setTimer, "2000" },
        }
  }; 
csmState stQcErrNoMi =  // TBookCMS[56] 
  {  56, "stQcErrNoMi", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 56, 32, 56, 56, 56, 56, 56, 56, 33, 31,  0, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, 56, },
     3, {  
          { writeMsg, "no_Minus" },
          { bgLED, "R9_6" },
          { playTune, "H.*_H.*_H.*_H.*_" },
        }
  }; 
csmState stQcSkip =  // TBookCMS[57] 
  {  57, "stQcSkip", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 77, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, 57, },
     1, {  
          { playTune, "E.C.*" },
        }
  }; 
csmState stQc6 =  // TBookCMS[58] 
  {  58, "stQc6", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 59, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, 58, },
     2, {  
          { finishRec, "" },
          { playTune, "E." },
        }
  }; 
csmState stQc6b =  // TBookCMS[59] 
  {  59, "stQc6b", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 59, 59, 59, 59, 59, 60, 59, 59, 59, 59, 61, 59, 59, 59, 59, 60, 59, 59, 59, 59, 61, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, 59, },
    0
  }; 
csmState stQc7 =  // TBookCMS[60] 
  {  60, "stQc7", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 62, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60, },
     2, {  
          { LED, "G!" },
          { playRec, "" },
        }
  }; 
csmState stQcErrNoTr =  // TBookCMS[61] 
  {  61, "stQcErrNoTr", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 61, 32, 61, 61, 61, 61, 61, 61, 33, 31,  0, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, 61, },
     3, {  
          { writeMsg, "no_Tree" },
          { bgLED, "R9_6" },
          { playTune, "H.*_H.*_H.*_H.*_" },
        }
  }; 
csmState stQc7b =  // TBookCMS[62] 
  {  62, "stQc7b", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 63, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, 62, },
     2, {  
          { LED, "_" },
          { playTune, "G." },
        }
  }; 
csmState stQc8 =  // TBookCMS[63] 
  {  63, "stQc8", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 63, 50, 64, 50, 50, 50, 50, 50, 50, 50, 65, 50, 64, 50, 50, 50, 50, 50, 50, 50, 65, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, 63, },
    0
  }; 
csmState stQc9 =  // TBookCMS[64] 
  {  64, "stQc9", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 64, 50, 50, 50, 50, 50, 66, 50, 50, 50, 67, 50, 50, 50, 50, 50, 66, 50, 50, 50, 67, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, },
     2, {  
          { LED, "G3" },
          { playTune, "C." },
        }
  }; 
csmState stQcErrPlay =  // TBookCMS[65] 
  {  65, "stQcErrPlay", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 65, 32, 65, 65, 65, 65, 65, 65, 33, 31,  0, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, 65, },
     3, {  
          { writeMsg, "rec_Play" },
          { bgLED, "R9_6" },
          { playTune, "H.*_H.*_H.*_H.*_" },
        }
  }; 
csmState stQc10 =  // TBookCMS[66] 
  {  66, "stQc10", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 66, 50, 50, 50, 50, 50, 50, 50, 68, 50, 69, 50, 50, 50, 50, 50, 50, 50, 68, 50, 69, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, 66, },
     2, {  
          { LED, "G3" },
          { playTune, "D." },
        }
  }; 
csmState stQcErrNoLh =  // TBookCMS[67] 
  {  67, "stQcErrNoLh", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 67, 32, 67, 67, 67, 67, 67, 67, 33, 31,  0, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, 67, },
     3, {  
          { writeMsg, "no_Lhand" },
          { bgLED, "R9_6" },
          { playTune, "H.*_H.*_H.*_H.*_" },
        }
  }; 
csmState stQc11 =  // TBookCMS[68] 
  {  68, "stQc11", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 68, 50, 50, 50, 50, 50, 50, 70, 50, 50, 71, 50, 50, 50, 50, 50, 50, 70, 50, 50, 71, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, },
     2, {  
          { LED, "G3" },
          { playTune, "E." },
        }
  }; 
csmState stQcErrNoPo =  // TBookCMS[69] 
  {  69, "stQcErrNoPo", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 69, 32, 69, 69, 69, 69, 69, 69, 33, 31,  0, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, },
     3, {  
          { writeMsg, "no_Pot" },
          { bgLED, "R9_6" },
          { playTune, "H.*_H.*_H.*_H.*_" },
        }
  }; 
csmState stQc12 =  // TBookCMS[70] 
  {  70, "stQc12", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 70, 50, 50, 50, 50, 50, 50, 50, 50, 72, 73, 50, 50, 50, 50, 50, 50, 50, 50, 72, 73, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70, },
     2, {  
          { LED, "G3" },
          { playTune, "F." },
        }
  }; 
csmState stQcErrNoRh =  // TBookCMS[71] 
  {  71, "stQcErrNoRh", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 71, 32, 71, 71, 71, 71, 71, 71, 33, 31,  0, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, 71, },
     3, {  
          { writeMsg, "no_Rhand" },
          { bgLED, "R9_6" },
          { playTune, "H.*_H.*_H.*_H.*_" },
        }
  }; 
csmState stQc13 =  // TBookCMS[72] 
  {  72, "stQc13", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 72, 50, 50, 50, 50, 50, 50, 50, 50, 75, 74, 50, 50, 50, 50, 50, 50, 50, 50, 75, 74, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, 72, },
     2, {  
          { LED, "G3" },
          { playTune, "G." },
        }
  }; 
csmState stQcErrNoSt =  // TBookCMS[73] 
  {  73, "stQcErrNoSt", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 73, 32, 73, 73, 73, 73, 73, 73, 33, 31,  0, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, 73, },
     3, {  
          { writeMsg, "no_Star" },
          { bgLED, "R9_6" },
          { playTune, "H.*_H.*_H.*_H.*_" },
        }
  }; 
csmState stQc14 =  // TBookCMS[74] 
  {  74, "stQc14", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 76, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, 74, },
     1, {  
          { playTune, "E.C.*" },
        }
  }; 
csmState stQcErrNoTa =  // TBookCMS[75] 
  {  75, "stQcErrNoTa", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 75, 32, 75, 75, 75, 75, 75, 75, 33, 31,  0, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, 75, },
     3, {  
          { writeMsg, "no_Table" },
          { bgLED, "R9_6" },
          { playTune, "H.*_H.*_H.*_H.*_" },
        }
  }; 
csmState stQc15 =  // TBookCMS[76] 
  {  76, "stQc15", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 76, 32, 76, 76, 76, 76, 76, 76, 33, 31,  0, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, 76, },
     2, {  
          { writeMsg, "QC_OK" },
          { bgLED, "G2_8" },
        }
  }; 
csmState stQcSkip2 =  // TBookCMS[77] 
  {  77, "stQcSkip2", 
//     N   H   C   P   M   T   L   R   p   S   t   H_  C_  P_  M_  T_  L_  R_  p_  S_  t_  sH  sC  sP  sM  sT  sL  sR  sp  sS  st  As  Ad  sI  lI  lB  cB  CB  FU  T   cF  lH  mH
     { 77, 32, 77, 77, 77, 77, 77, 77, 33, 31,  0, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, 77, },
     2, {  
          { writeMsg, "QC_OK_short" },
          { bgLED, "G2_8" },
        }
  }; 
csmState * TBookCSM[] = { 
  &stQcTest,  // TBookCMS[0] 
  &stWakeup,  // TBookCMS[1] 
  &stSleepy,  // TBookCMS[2] 
  &stCloseUSB,  // TBookCMS[3] 
  &stPlayLouder,  // TBookCMS[4] 
  &stPlaySofter,  // TBookCMS[5] 
  &stPlayPause,  // TBookCMS[6] 
  &stPlayJumpBack,  // TBookCMS[7] 
  &stPlayJumpFwd,  // TBookCMS[8] 
  &stPlayResume,  // TBookCMS[9] 
  &stOnPrevSubj,  // TBookCMS[10] 
  &stOnNextSubj,  // TBookCMS[11] 
  &stOnNextMsg,  // TBookCMS[12] 
  &stOnPrevMsg,  // TBookCMS[13] 
  &stWait,  // TBookCMS[14] 
  &stOnFeedback,  // TBookCMS[15] 
  &stFbOptions,  // TBookCMS[16] 
  &stStartRec,  // TBookCMS[17] 
  &stPauseRec,  // TBookCMS[18] 
  &stFinishRec,  // TBookCMS[19] 
  &stPlayRec,  // TBookCMS[20] 
  &stCancelRec,  // TBookCMS[21] 
  &stSaveRec,  // TBookCMS[22] 
  &stLowBatt,  // TBookCMS[23] 
  &stUSBmode,  // TBookCMS[24] 
  &stIdleLouder,  // TBookCMS[25] 
  &stIdleSofter,  // TBookCMS[26] 
  &stTest,  // TBookCMS[27] 
  &stOnUpdate,  // TBookCMS[28] 
  &stNxtPkg,  // TBookCMS[29] 
  &stChgPkg,  // TBookCMS[30] 
  &stQcUSB,  // TBookCMS[31] 
  &stQcReboot,  // TBookCMS[32] 
  &stQcSysTest,  // TBookCMS[33] 
  &stWelcoming,  // TBookCMS[34] 
  &stPromptSubj,  // TBookCMS[35] 
  &stPromptingSub,  // TBookCMS[36] 
  &stUnSleepy,  // TBookCMS[37] 
  &stGoSleep,  // TBookCMS[38] 
  &stFallAsleep,  // TBookCMS[39] 
  &stAnnouncing,  // TBookCMS[40] 
  &stInvitation,  // TBookCMS[41] 
  &stPromptNextSubj,  // TBookCMS[42] 
  &stPlaying,  // TBookCMS[43] 
  &stOnLowBatt,  // TBookCMS[44] 
  &stOnCharging,  // TBookCMS[45] 
  &stGoFWU,  // TBookCMS[46] 
  &stQc1,  // TBookCMS[47] 
  &stQc2,  // TBookCMS[48] 
  &stQcErrFiles,  // TBookCMS[49] 
  &stQcBeep,  // TBookCMS[50] 
  &stQc3,  // TBookCMS[51] 
  &stQcErrGrn,  // TBookCMS[52] 
  &stQc4,  // TBookCMS[53] 
  &stQcErrRed,  // TBookCMS[54] 
  &stQc5,  // TBookCMS[55] 
  &stQcErrNoMi,  // TBookCMS[56] 
  &stQcSkip,  // TBookCMS[57] 
  &stQc6,  // TBookCMS[58] 
  &stQc6b,  // TBookCMS[59] 
  &stQc7,  // TBookCMS[60] 
  &stQcErrNoTr,  // TBookCMS[61] 
  &stQc7b,  // TBookCMS[62] 
  &stQc8,  // TBookCMS[63] 
  &stQc9,  // TBookCMS[64] 
  &stQcErrPlay,  // TBookCMS[65] 
  &stQc10,  // TBookCMS[66] 
  &stQcErrNoLh,  // TBookCMS[67] 
  &stQc11,  // TBookCMS[68] 
  &stQcErrNoPo,  // TBookCMS[69] 
  &stQc12,  // TBookCMS[70] 
  &stQcErrNoRh,  // TBookCMS[71] 
  &stQc13,  // TBookCMS[72] 
  &stQcErrNoSt,  // TBookCMS[73] 
  &stQc14,  // TBookCMS[74] 
  &stQcErrNoTa,  // TBookCMS[75] 
  &stQc15,  // TBookCMS[76] 
  &stQcSkip2,  // TBookCMS[77] 
};  // end of tbook_csm_def.h
