//TBook Control State Machine definition--   tbook_csm.def 
// generated by writeCSM() 
#include "controlmanager.h" 
TBConfig_t  TB_Config = { 
                       6,   // default_volume 
                       5,   // default_speed 
                  300000,   // powerCheckMS 
                    5000,   // shortIdleMS 
                   20000,   // longIdleMS 
     "M0:/system/audio/",   // systemAudio 
                      50,   // minShortPressMS 
                    1000,   // minLongPressMS 
                       0,   // initState 
                  "_49G",   // bgPulse 
                    "G!",   // fgPlaying 
                 "G2_3!",   // fgPlayPaused 
                    "R!",   // fgRecording 
                 "R2_3!",   // fgRecordPaused 
                    "O!",   // fgSavingRec 
                "G3_3G3",   // fgSaveRec 
                "R3_3R3",   // fgCancelRec 
                 "O5o5!",   // fgUSB_MSC 
        "R8_2R8_2R8_20!",   // fgTB_Error 
       "_3R3_3R3_3R3_5!",   // fgNoUSBcable 
                 "G5g5!",   // fgUSBconnect 
    "G_3G_3G_9G_3G_9G_3",   // fgPowerDown 
    "O3_5O3_3O3_2O3_1O3"    // fgEnterDFU 
};  // TB_Config 

int   nPlaySys = 6;  // PlaySys prompts used by CSM 
SysAudio_t	SysAudio[] = { 
  { "welcome",   "M0:/system/audio/welcome.wav" }, 
  { "rh_for_subj",   "M0:/system/audio/rh_for_subj.wav" }, 
  { "rh_for_nxt_subj",   "M0:/system/audio/rh_for_nxt_subj.wav" }, 
  { "cir_record_ideas",   "M0:/system/audio/cir_record_ideas.wav" }, 
  { "louder",   "M0:/system/audio/louder.wav" }, 
  { "softer",   "M0:/system/audio/softer.wav" }  
};  // SysAudio 

int   nCSMstates = 44;  // TBook state machine definition 
csmState stWakeup =  // TBookCMS[0] 
  { 0, "stWakeup", { 
     0,  0,  0,  2,  3,  9,  7,  8,  4,  0, 10,  1,  0,  0,  0,  0,  5,  6,  0,  0,  0,  0, 
    12,  0,  0,  0,  0,  0,  0,  0,  0, 11, 13, 11,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  },
    4,
    { 
      {        LED, "_" }, 
      {      bgLED, "G_29" }, 
      {  changePkg, "" }, 
      {    playSys, "welcome" } 
    }
  }; 
csmState stSleepy =  // TBookCMS[1] 
  { 0, "stSleepy", { 
    25,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 26,  1,  1,  1,  1,  },
    3,
    { 
      {      bgLED, "O_9" }, 
      {     saveSt, "1" }, 
      {   setTimer, "10000" } 
    }
  }; 
csmState stPlayLouder =  // TBookCMS[2] 
  { 0, "stPlayLouder", { 
     2,  0,  2,  2,  3,  2,  2,  2,  4,  2,  2,  1,  0,  2,  2,  2,  5,  6,  2,  2,  2,  2, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  },
    2,
    { 
      {     volAdj, "1" }, 
      {   goPrevSt, "" } 
    }
  }; 
csmState stPlaySofter =  // TBookCMS[3] 
  { 0, "stPlaySofter", { 
     3,  0,  3,  2,  3,  3,  3,  3,  4,  3,  3,  1,  0,  3,  3,  3,  5,  6,  3,  3,  3,  3, 
     3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  1,  3,  3,  3,  3,  3,  3,  3,  3,  3,  },
    2,
    { 
      {     volAdj, "-1" }, 
      {   goPrevSt, "" } 
    }
  }; 
csmState stPlayPause =  // TBookCMS[4] 
  { 0, "stPlayPause", { 
     4,  0,  4,  2,  3,  9,  7,  8, 28,  4, 10,  1,  0,  4,  4,  4,  5,  6,  4,  4,  4,  4, 
    12,  4,  4,  4,  4,  4,  4,  4,  4, 11,  4, 11,  1,  4,  4,  4,  4,  4,  4,  4,  4,  4,  },
    2,
    { 
      {     saveSt, "2" }, 
      {  pausePlay, "" } 
    }
  }; 
csmState stPlayJumpBack =  // TBookCMS[5] 
  { 0, "stPlayJumpBack", { 
     5,  0,  5,  2,  3,  9,  7,  8,  4,  5, 10,  1,  0,  5,  5,  5,  5,  6,  5,  5,  5,  5, 
    12,  5,  5,  5,  5,  5,  5,  5,  5, 11,  5, 11,  1,  5,  5,  5,  5,  5,  5,  5,  5,  5,  },
    1,
    { 
      {     posAdj, "-7" } 
    }
  }; 
csmState stPlayJumpFwd =  // TBookCMS[6] 
  { 0, "stPlayJumpFwd", { 
     6,  0,  6,  2,  3,  9,  7,  8,  4,  6, 10,  1,  0,  6,  6,  6,  5,  6,  6,  6,  6,  6, 
    12,  6,  6,  6,  6,  6,  6,  6,  6, 11,  6, 11,  1,  6,  6,  6,  6,  6,  6,  6,  6,  6,  },
    1,
    { 
      {     posAdj, "60" } 
    }
  }; 
csmState stOnPrevSubj =  // TBookCMS[7] 
  { 0, "stOnPrevSubj", { 
     7,  0,  7,  2,  3,  9,  7,  8,  4,  7, 10,  1,  0,  7,  7,  7,  5,  6,  7,  7,  7,  7, 
    12,  7,  7,  7,  7,  7,  7,  7,  7, 11, 29, 11,  1,  7,  7,  7,  7,  7,  7,  7,  7,  7,  },
    2,
    { 
      {    subjAdj, "-1" }, 
      {   playSubj, "nm" } 
    }
  }; 
csmState stOnNextSubj =  // TBookCMS[8] 
  { 0, "stOnNextSubj", { 
     8,  0,  8,  2,  3,  9,  7,  8,  4,  8, 10,  1,  0,  8,  8,  8,  5,  6,  8,  8,  8,  8, 
    12,  8,  8,  8,  8,  8,  8,  8,  8, 11, 29, 11,  1,  8,  8,  8,  8,  8,  8,  8,  8,  8,  },
    2,
    { 
      {    subjAdj, "1" }, 
      {   playSubj, "nm" } 
    }
  }; 
csmState stOnNextMsg =  // TBookCMS[9] 
  { 0, "stOnNextMsg", { 
     9,  0,  9,  2,  3,  9,  7,  8,  4,  9, 10,  1,  0,  9,  9,  9,  5,  6,  9,  9,  9,  9, 
    12,  9,  9,  9,  9,  9,  9,  9,  9, 11, 32, 11,  1,  9,  9,  9,  9,  9,  9,  9,  9,  9,  },
    2,
    { 
      {     msgAdj, "1" }, 
      {   playSubj, "msg" } 
    }
  }; 
csmState stOnPrevMsg =  // TBookCMS[10] 
  { 0, "stOnPrevMsg", { 
    10,  0, 10,  2,  3,  9,  7,  8,  4, 10, 10,  1,  0, 10, 10, 10,  5,  6, 10, 10, 10, 10, 
    12, 10, 10, 10, 10, 10, 10, 10, 10, 11, 32, 11,  1, 10, 10, 10, 10, 10, 10, 10, 10, 10,  },
    2,
    { 
      {     msgAdj, "-1" }, 
      {   playSubj, "msg" } 
    }
  }; 
csmState stWait =  // TBookCMS[11] 
  { 0, "stWait", { 
    17,  0, 11, 19, 20,  9,  7,  8, 11, 11, 10,  1,  0, 11, 11, 11, 11, 11, 11, 11, 11, 11, 
    12, 18, 22, 11, 11, 24, 23, 11, 21, 11, 11, 11,  1, 16, 11, 11, 11, 11, 11, 11, 11, 11,  },
    0 
  }; 
csmState stOnFeedback =  // TBookCMS[12] 
  { 0, "stOnFeedback", { 
    12,  0, 34, 12, 12, 12, 12, 12, 12, 33, 12,  1,  0, 12, 12, 12, 12, 12, 12, 12, 12, 12, 
    12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,  1, 12, 12, 12, 12, 12, 12, 12, 12, 12,  },
    1,
    { 
      {    playSys, "cir_record_ideas" } 
    }
  }; 
csmState stWelcoming =  // TBookCMS[13] 
  { 0, "stWelcoming", { 
    13,  0, 13,  2,  3,  9,  7,  8,  4, 13, 10,  1,  0, 13, 13, 13,  5,  6, 13, 13, 13, 13, 
    12, 13, 13, 13, 13, 13, 13, 13, 13, 14, 13, 11,  1, 13, 13, 13, 13, 13, 13, 13, 13, 13,  },
    0 
  }; 
csmState stPromptSubj =  // TBookCMS[14] 
  { 0, "stPromptSubj", { 
    14,  0, 14,  2,  3,  9,  7,  8,  4, 14, 10,  1,  0, 14, 14, 14,  5,  6, 14, 14, 14, 14, 
    12, 14, 14, 14, 14, 14, 14, 14, 14, 11, 15, 11,  1, 14, 14, 14, 14, 14, 14, 14, 14, 14,  },
    1,
    { 
      {    playSys, "rh_for_subj" } 
    }
  }; 
csmState stPromptingSub =  // TBookCMS[15] 
  { 0, "stPromptingSub", { 
    15,  0, 15,  2,  3,  9,  7,  8,  4, 15, 10,  1,  0, 15, 15, 15,  5,  6, 15, 15, 15, 15, 
    12, 15, 15, 15, 15, 15, 15, 15, 15, 11, 15, 11,  1, 15, 15, 15, 15, 15, 15, 15, 15, 15,  },
    0 
  }; 
csmState stLowBatt =  // TBookCMS[16] 
  { 0, "stLowBatt", { 
    17,  0, 16, 19, 20, 16, 16, 16, 16, 16, 16,  1,  0, 16, 16, 16, 16, 16, 16, 16, 16, 16, 
    16, 18, 22, 16, 16, 24, 23, 16, 21, 16, 16, 16,  1, 16, 16, 16, 16, 16, 16, 16, 16, 16,  },
    0 
  }; 
csmState stGoFWU =  // TBookCMS[17] 
  { 0, "stGoFWU", { 
    17,  0, 17, 17, 17, 17, 17, 17, 17, 17, 17,  1,  0, 17, 17, 17, 17, 17, 17, 17, 17, 17, 
    17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,  1, 17, 17, 17, 17, 17, 17, 17, 17, 17,  },
    0 
  }; 
csmState stUSBmode =  // TBookCMS[18] 
  { 0, "stUSBmode", { 
    18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 
    18, 42, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,  },
    2,
    { 
      {      bgLED, "O2_8" }, 
      {   startUSB, "" } 
    }
  }; 
csmState stIdleLouder =  // TBookCMS[19] 
  { 0, "stIdleLouder", { 
    19,  0, 19,  2,  3, 19, 19, 19,  4, 19, 19,  1,  0, 19, 19, 19,  5,  6, 19, 19, 19, 19, 
    19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19,  1, 19, 19, 19, 19, 19, 19, 19, 19, 19,  },
    3,
    { 
      {     volAdj, "1" }, 
      {    playSys, "louder" }, 
      {   goPrevSt, "" } 
    }
  }; 
csmState stIdleSofter =  // TBookCMS[20] 
  { 0, "stIdleSofter", { 
    20,  0, 20,  2,  3, 20, 20, 20,  4, 20, 20,  1,  0, 20, 20, 20,  5,  6, 20, 20, 20, 20, 
    20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20,  1, 20, 20, 20, 20, 20, 20, 20, 20, 20,  },
    3,
    { 
      {     volAdj, "-1" }, 
      {    playSys, "softer" }, 
      {   goPrevSt, "" } 
    }
  }; 
csmState stTest =  // TBookCMS[21] 
  { 0, "stTest", { 
    21,  0, 21, 21, 21, 21, 21, 21, 21, 21, 21,  1,  0, 21, 21, 21, 21, 21, 21, 21, 21, 21, 
    21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21, 21,  1, 21, 21, 21, 21, 21, 21, 21, 21, 21,  },
    1,
    { 
      {    sysTest, "" } 
    }
  }; 
csmState stOnUpdate =  // TBookCMS[22] 
  { 0, "stOnUpdate", { 
    22,  0, 22, 22, 22, 22, 22, 22, 22, 22, 22,  1,  0, 22, 22, 22, 22, 22, 22, 22, 22, 22, 
    22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,  1, 22, 22, 22, 22, 22, 22, 22, 22, 22,  },
    1,
    { 
      {    sysBoot, "" } 
    }
  }; 
csmState stNxtPkg =  // TBookCMS[23] 
  { 0, "stNxtPkg", { 
    17,  0, 23, 19, 20, 23, 23, 23, 23, 23, 23,  1,  0, 23, 23, 23, 23, 23, 23, 23, 23, 23, 
    23, 18, 22, 23, 23, 24, 23, 23, 21, 23, 23, 23,  1, 16, 23, 23, 23, 23, 23, 23, 23, 23,  },
    1,
    { 
      { playNxtPkg, "" } 
    }
  }; 
csmState stChgPkg =  // TBookCMS[24] 
  { 0, "stChgPkg", { 
    17,  0, 24, 19, 20,  9,  7,  8, 24, 24, 10,  1,  0, 24, 24, 24, 24, 24, 24, 24, 24, 24, 
    12, 18, 22, 24, 24, 24, 23, 24, 21, 11, 24, 11,  1, 16, 24, 24, 24, 24, 24, 24, 24, 24,  },
    1,
    { 
      {  changePkg, "" } 
    }
  }; 
csmState stUnSleepy =  // TBookCMS[25] 
  { 0, "stUnSleepy", { 
    25,  0, 25, 25, 25, 25, 25, 25, 25, 25, 25,  1,  0, 25, 25, 25, 25, 25, 25, 25, 25, 25, 
    25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25,  1, 25, 25, 25, 25, 25, 25, 25, 25, 25,  },
    2,
    { 
      {      bgLED, "G_29" }, 
      {  goSavedSt, "1" } 
    }
  }; 
csmState stGoSleep =  // TBookCMS[26] 
  { 0, "stGoSleep", { 
    26,  0,  0, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 
    26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 26, 26, 26, 26,  },
    2,
    { 
      {      bgLED, "R_4" }, 
      {   setTimer, "2000" } 
    }
  }; 
csmState stFallAsleep =  // TBookCMS[27] 
  { 0, "stFallAsleep", { 
    27,  0,  0, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 
    27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,  },
    1,
    { 
      {  powerDown, "" } 
    }
  }; 
csmState stPlayResume =  // TBookCMS[28] 
  { 0, "stPlayResume", { 
    28,  0, 28,  2,  3,  9,  7,  8,  4, 28, 10,  1,  0, 28, 28, 28,  5,  6, 28, 28, 28, 28, 
    12, 28, 28, 28, 28, 28, 28, 28, 28, 11, 28, 11,  1, 28, 28, 28, 28, 28, 28, 28, 28, 28,  },
    2,
    { 
      { resumePlay, "" }, 
      {  goSavedSt, "2" } 
    }
  }; 
csmState stAnnouncing =  // TBookCMS[29] 
  { 0, "stAnnouncing", { 
    29,  0, 29,  2,  3,  9,  7,  8,  4, 29, 10,  1,  0, 29, 29, 29,  5,  6, 29, 29, 29, 29, 
    12, 29, 29, 29, 29, 29, 29, 29, 29, 30, 29, 11,  1, 29, 29, 29, 29, 29, 29, 29, 29, 29,  },
    0 
  }; 
csmState stInvitation =  // TBookCMS[30] 
  { 0, "stInvitation", { 
    30,  0, 30,  2,  3,  9,  7,  8,  4, 30, 10,  1,  0, 30, 30, 30,  5,  6, 30, 30, 30, 30, 
    12, 30, 30, 30, 30, 30, 30, 30, 30, 31, 30, 11,  1, 30, 30, 30, 30, 30, 30, 30, 30, 30,  },
    1,
    { 
      {   playSubj, "pr" } 
    }
  }; 
csmState stPromptNextSubj =  // TBookCMS[31] 
  { 0, "stPromptNextSubj", { 
    31,  0, 31,  2,  3,  9,  7,  8,  4, 31, 10,  1,  0, 31, 31, 31,  5,  6, 31, 31, 31, 31, 
    12, 31, 31, 31, 31, 31, 31, 31, 31, 11, 31, 11,  1, 31, 31, 31, 31, 31, 31, 31, 31, 31,  },
    1,
    { 
      {    playSys, "rh_for_nxt_subj" } 
    }
  }; 
csmState stPlaying =  // TBookCMS[32] 
  { 0, "stPlaying", { 
    32,  0, 32,  2,  3,  9,  7,  8,  4, 32, 10,  1,  0, 32, 32, 32,  5,  6, 32, 32, 32, 32, 
    12, 32, 32, 32, 32, 32, 32, 32, 32, 11, 32, 11,  1, 32, 32, 32, 32, 32, 32, 32, 32, 32,  },
    0 
  }; 
csmState stFbOptions =  // TBookCMS[33] 
  { 0, "stFbOptions", { 
    33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 
    33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33,  },
    0 
  }; 
csmState stStartRec =  // TBookCMS[34] 
  { 0, "stStartRec", { 
    34,  0, 37, 34, 34, 38, 34, 34, 36, 40, 39,  1,  0, 34, 34, 34, 34, 34, 34, 34, 34, 34, 
    34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34,  1, 34, 34, 34, 34, 34, 34, 34, 34, 34,  },
    1,
    { 
      {   startRec, "" } 
    }
  }; 
csmState stOnOptions =  // TBookCMS[35] 
  { 0, "stOnOptions", { 
    35,  0, 35, 35, 35, 35, 35, 35, 35, 35, 35,  1,  0, 35, 35, 35, 35, 35, 35, 35, 35, 35, 
    35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,  1, 35, 35, 35, 35, 35, 35, 35, 35, 35,  },
    1,
    { 
      {    playSys, "" } 
    }
  }; 
csmState stPauseRec =  // TBookCMS[36] 
  { 0, "stPauseRec", { 
    36,  0, 37, 36, 36, 38, 36, 36, 36, 40, 39,  1,  0, 36, 36, 36, 36, 36, 36, 36, 36, 36, 
    36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,  1, 36, 36, 36, 36, 36, 36, 36, 36, 36,  },
    2,
    { 
      {     saveSt, "2" }, 
      {   pauseRec, "" } 
    }
  }; 
csmState stFinishRec =  // TBookCMS[37] 
  { 0, "stFinishRec", { 
    37,  0, 37, 37, 37, 38, 37, 37, 36, 40, 39,  1,  0, 37, 37, 37, 37, 37, 37, 37, 37, 37, 
    37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37, 37,  1, 37, 37, 37, 37, 37, 37, 37, 37, 37,  },
    1,
    { 
      {  finishRec, "" } 
    }
  }; 
csmState stPlayRec =  // TBookCMS[38] 
  { 0, "stPlayRec", { 
    38,  0, 37, 38, 38, 38, 38, 38, 36, 40, 39,  1,  0, 38, 38, 38, 38, 38, 38, 38, 38, 38, 
    38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38,  1, 38, 38, 38, 38, 38, 38, 38, 38, 38,  },
    1,
    { 
      {    playRec, "" } 
    }
  }; 
csmState stCancelRec =  // TBookCMS[39] 
  { 0, "stCancelRec", { 
    39,  0, 39, 39, 39,  9,  7,  8, 39, 39, 10,  1,  0, 39, 39, 39, 39, 39, 39, 39, 39, 39, 
    12, 39, 39, 39, 39, 39, 39, 39, 39, 11, 39, 11,  1, 39, 39, 39, 39, 39, 39, 39, 39, 39,  },
    1,
    { 
      {    saveRec, "del" } 
    }
  }; 
csmState stSaveRec =  // TBookCMS[40] 
  { 0, "stSaveRec", { 
    40,  0, 40, 40, 40,  9,  7,  8, 40, 40, 10,  1,  0, 40, 40, 40, 40, 40, 40, 40, 40, 40, 
    12, 40, 40, 40, 40, 40, 40, 40, 40, 11, 40, 11,  1, 40, 40, 40, 40, 40, 40, 40, 40, 40,  },
    1,
    { 
      {    saveRec, "sv" } 
    }
  }; 
csmState stOnLowBatt =  // TBookCMS[41] 
  { 0, "stOnLowBatt", { 
    41,  0, 41, 41, 41, 41, 41, 41, 41, 41, 41,  1,  0, 41, 41, 41, 41, 41, 41, 41, 41, 41, 
    41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,  1, 41, 41, 41, 41, 41, 41, 41, 41, 41,  },
    1,
    { 
      {      bgLED, "R_9" } 
    }
  }; 
csmState stCloseUSB =  // TBookCMS[42] 
  { 0, "stCloseUSB", { 
    42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 
    42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42,  0, 42, 42, 42, 42,  },
    3,
    { 
      {     endUSB, "" }, 
      {      bgLED, "G_29" }, 
      {   setTimer, "1000" } 
    }
  }; 
csmState stOnCharging =  // TBookCMS[43] 
  { 0, "stOnCharging", { 
    17,  0, 43, 19, 20, 43, 43, 43, 43, 43, 43,  1,  0, 43, 43, 43, 43, 43, 43, 43, 43, 43, 
    43, 18, 22, 43, 43, 24, 23, 43, 21, 43, 43, 43,  1, 16, 43, 43, 43, 43, 43, 43, 43, 43,  },
    2,
    { 
      { showCharge, "" }, 
      {   goPrevSt, "" } 
    }
  }; 

csmState * TBookCSM[] = { 
&stWakeup,  // TBookCSM[0]
&stSleepy,  // TBookCSM[1]
&stPlayLouder,  // TBookCSM[2]
&stPlaySofter,  // TBookCSM[3]
&stPlayPause,  // TBookCSM[4]
&stPlayJumpBack,  // TBookCSM[5]
&stPlayJumpFwd,  // TBookCSM[6]
&stOnPrevSubj,  // TBookCSM[7]
&stOnNextSubj,  // TBookCSM[8]
&stOnNextMsg,  // TBookCSM[9]
&stOnPrevMsg,  // TBookCSM[10]
&stWait,  // TBookCSM[11]
&stOnFeedback,  // TBookCSM[12]
&stWelcoming,  // TBookCSM[13]
&stPromptSubj,  // TBookCSM[14]
&stPromptingSub,  // TBookCSM[15]
&stLowBatt,  // TBookCSM[16]
&stGoFWU,  // TBookCSM[17]
&stUSBmode,  // TBookCSM[18]
&stIdleLouder,  // TBookCSM[19]
&stIdleSofter,  // TBookCSM[20]
&stTest,  // TBookCSM[21]
&stOnUpdate,  // TBookCSM[22]
&stNxtPkg,  // TBookCSM[23]
&stChgPkg,  // TBookCSM[24]
&stUnSleepy,  // TBookCSM[25]
&stGoSleep,  // TBookCSM[26]
&stFallAsleep,  // TBookCSM[27]
&stPlayResume,  // TBookCSM[28]
&stAnnouncing,  // TBookCSM[29]
&stInvitation,  // TBookCSM[30]
&stPromptNextSubj,  // TBookCSM[31]
&stPlaying,  // TBookCSM[32]
&stFbOptions,  // TBookCSM[33]
&stStartRec,  // TBookCSM[34]
&stOnOptions,  // TBookCSM[35]
&stPauseRec,  // TBookCSM[36]
&stFinishRec,  // TBookCSM[37]
&stPlayRec,  // TBookCSM[38]
&stCancelRec,  // TBookCSM[39]
&stSaveRec,  // TBookCSM[40]
&stOnLowBatt,  // TBookCSM[41]
&stCloseUSB,  // TBookCSM[42]
&stOnCharging  // TBookCSM[43]
};  // end of TBookCSM.c 
