/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.3.0
 *
 * Project: 'TBook_Rev2b+TBv2b' 
 * Target:  'TBv2b' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Keil::Device:STM32Cube HAL:Common@1.8.1 */
#define USE_HAL_DRIVER


#endif /* PRE_INCLUDE_GLOBAL_H */
