// preloaded TBook Control State Machine   preloadCSM.c
// generated by CSMcompile version: 8(2021-10-15)
// run at 2021-10-15 13:50:41
// from C:\Users\geneb\Documents\CSMcompile\data\control_def.txt of: 2021-10-12 16:13:30
#include "packageData.h" 
//Ver:   // TB CSM 2021-10-12: vPRE QC_preload version 
static TBConfig_t  preTB_Config = { 
  6,  // default_volume 
  300000,  // powerCheckMS 
  5000,  // shortIdleMS 
  20000,  // longIdleMS 
  50,  // minShortPressMS 
  1000,  // minLongPressMS 
  0, // qcTestState 
  0, // initState 
  "system/audio/",  // systemAudio 
  "_49G",  // bgPulse 
  "G!",  // fgPlaying 
  "G2_3!",  // fgPlayPaused 
  "R!",  // fgRecording 
  "R2_3!",  // fgRecordPaused 
  "O!",  // fgSavingRec 
  "G3_3G3",  // fgSaveRec 
  "R3_3R3",  // fgCancelRec 
  "O5o5!",  // fgUSB_MSC 
  "R8_2R8_2R8_20!",  // fgTB_Error 
  "_3R3_3R3_3R3_5!",  // fgNoUSBcable 
  "G5g5!",  // fgUSBconnect 
  "G_3G_3G_9G_3G_9G_3",  // fgPowerDown 
};  // preTB_Config
 
static AudioList_t preSysAudio[] = { 
0,  // # PlaySys prompts used by CSM 
{ "welcome" }
};  // preSysAudio 
 
static csmAction_t  a_stQcTest_0       = { playTune, "C/" };
static ActionList_t a_stQcTest         = { 1, { &a_stQcTest_0 } };
static short        n_stQcTest[]       = {  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static CState_t     stQcTest           = { 0, "stQcTest", 45, n_stQcTest, &a_stQcTest };  // [0] 
 
static csmAction_t  a_stQcUSB_0        = { bgLED, "O2_8" };
static csmAction_t  a_stQcUSB_1        = { startUSB, "" };
static ActionList_t a_stQcUSB          = { 2, { &a_stQcUSB_0, &a_stQcUSB_1 } };
static short        n_stQcUSB[]        = {  1, 2, 1, 1, 1, 1, 1, 1, 3, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1};
static CState_t     stQcUSB            = { 1, "stQcUSB", 45, n_stQcUSB, &a_stQcUSB };  // [1] 
 
static csmAction_t  a_stQcReboot_0     = { sysBoot, "" };
static ActionList_t a_stQcReboot       = { 1, { &a_stQcReboot_0 } };
static short        n_stQcReboot[]     = {  2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2};
static CState_t     stQcReboot         = { 2, "stQcReboot", 45, n_stQcReboot, &a_stQcReboot };  // [2] 
 
static csmAction_t  a_stQcSysTest_0    = { playTune, "CG/.FDEH.G/" };
static ActionList_t a_stQcSysTest      = { 1, { &a_stQcSysTest_0 } };
static short        n_stQcSysTest[]    = {  3, 2, 3, 3, 3, 3, 3, 3, 3, 1, 0, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3};
static CState_t     stQcSysTest        = { 3, "stQcSysTest", 45, n_stQcSysTest, &a_stQcSysTest };  // [3] 
 
static csmAction_t  a_stQc1_0          = { filesTest, "" };
static csmAction_t  a_stQc1_1          = { bgLED, "G3_3" };
static ActionList_t a_stQc1            = { 2, { &a_stQc1_0, &a_stQc1_1 } };
static short        n_stQc1[]          = {  4, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 6};
static CState_t     stQc1              = { 4, "stQc1", 45, n_stQc1, &a_stQc1 };  // [4] 
 
static csmAction_t  a_stQc2_0          = { bgLED, "G3_3" };
static csmAction_t  a_stQc2_1          = { playTune, "C/C/" };
static ActionList_t a_stQc2            = { 2, { &a_stQc2_0, &a_stQc2_1 } };
static short        n_stQc2[]          = {  5, 7, 7, 8, 7, 7, 7, 7, 7, 7, 9, 7, 7, 8, 7, 7, 7, 7, 7, 7, 9, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5};
static CState_t     stQc2              = { 5, "stQc2", 45, n_stQc2, &a_stQc2 };  // [5] 
 
static csmAction_t  a_stQcErrFiles_0   = { writeMsg, "filesTest" };
static csmAction_t  a_stQcErrFiles_1   = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrFiles_2   = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrFiles     = { 3, { &a_stQcErrFiles_0, &a_stQcErrFiles_1, &a_stQcErrFiles_2 } };
static short        n_stQcErrFiles[]   = {  6, 2, 6, 6, 6, 6, 6, 6, 3, 1, 0, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6};
static CState_t     stQcErrFiles       = { 6, "stQcErrFiles", 45, n_stQcErrFiles, &a_stQcErrFiles };  // [6] 
 
static csmAction_t  a_stQcBeep_0       = { playTune, "H_H" };
static csmAction_t  a_stQcBeep_1       = { goPrevSt, "" };
static ActionList_t a_stQcBeep         = { 2, { &a_stQcBeep_0, &a_stQcBeep_1 } };
static short        n_stQcBeep[]       = {  7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7};
static CState_t     stQcBeep           = { 7, "stQcBeep", 45, n_stQcBeep, &a_stQcBeep };  // [7] 
 
static csmAction_t  a_stQc3_0          = { bgLED, "R3_3" };
static csmAction_t  a_stQc3_1          = { playTune, "D/" };
static ActionList_t a_stQc3            = { 2, { &a_stQc3_0, &a_stQc3_1 } };
static short        n_stQc3[]          = {  8,10, 7, 7, 7, 7, 7, 7, 7, 7,11,10, 7, 7, 7, 7, 7, 7, 7, 7,11, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8};
static CState_t     stQc3              = { 8, "stQc3", 45, n_stQc3, &a_stQc3 };  // [8] 
 
static csmAction_t  a_stQcErrGrn_0     = { writeMsg, "no_Green" };
static csmAction_t  a_stQcErrGrn_1     = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrGrn_2     = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrGrn       = { 3, { &a_stQcErrGrn_0, &a_stQcErrGrn_1, &a_stQcErrGrn_2 } };
static short        n_stQcErrGrn[]     = {  9, 2, 9, 9, 9, 9, 9, 9, 3, 1, 0, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9};
static CState_t     stQcErrGrn         = { 9, "stQcErrGrn", 45, n_stQcErrGrn, &a_stQcErrGrn };  // [9] 
 
static csmAction_t  a_stQc4_0          = { bgLED, "_" };
static csmAction_t  a_stQc4_1          = { LED, "G3" };
static csmAction_t  a_stQc4_2          = { playTune, "E/" };
static ActionList_t a_stQc4            = { 3, { &a_stQc4_0, &a_stQc4_1, &a_stQc4_2 } };
static short        n_stQc4[]          = { 10, 7, 7, 7,12, 7, 7, 7, 7,14,13, 7, 7, 7,12, 7, 7, 7, 7,14,13, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,10,10,10,10,10,10,10,10,10,10,10,10,10,10};
static CState_t     stQc4              = { 10, "stQc4", 45, n_stQc4, &a_stQc4 };  // [10] 
 
static csmAction_t  a_stQcErrRed_0     = { writeMsg, "no_Red" };
static csmAction_t  a_stQcErrRed_1     = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrRed_2     = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrRed       = { 3, { &a_stQcErrRed_0, &a_stQcErrRed_1, &a_stQcErrRed_2 } };
static short        n_stQcErrRed[]     = { 11, 2,11,11,11,11,11,11, 3, 1, 0,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11};
static CState_t     stQcErrRed         = { 11, "stQcErrRed", 45, n_stQcErrRed, &a_stQcErrRed };  // [11] 
 
static csmAction_t  a_stQc5_0          = { startRec, "" };
static csmAction_t  a_stQc5_1          = { setTimer, "4000" };
static ActionList_t a_stQc5            = { 2, { &a_stQc5_0, &a_stQc5_1 } };
static short        n_stQc5[]          = { 12,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,12,12,12,12,12,12,12,12,15,12,12,12,12,12};
static CState_t     stQc5              = { 12, "stQc5", 45, n_stQc5, &a_stQc5 };  // [12] 
 
static csmAction_t  a_stQcErrNoMi_0    = { writeMsg, "no_Minus" };
static csmAction_t  a_stQcErrNoMi_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoMi_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoMi      = { 3, { &a_stQcErrNoMi_0, &a_stQcErrNoMi_1, &a_stQcErrNoMi_2 } };
static short        n_stQcErrNoMi[]    = { 13, 2,13,13,13,13,13,13, 3, 1, 0,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13,13};
static CState_t     stQcErrNoMi        = { 13, "stQcErrNoMi", 45, n_stQcErrNoMi, &a_stQcErrNoMi };  // [13] 
 
static csmAction_t  a_stQcSkip_0       = { playTune, "G/C" };
static ActionList_t a_stQcSkip         = { 1, { &a_stQcSkip_0 } };
static short        n_stQcSkip[]       = { 14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,14,34,14,14,14,14,14,14,14,14,14,14,14,14};
static CState_t     stQcSkip           = { 14, "stQcSkip", 45, n_stQcSkip, &a_stQcSkip };  // [14] 
 
static csmAction_t  a_stQc6_0          = { finishRec, "" };
static csmAction_t  a_stQc6_1          = { playTune, "F/" };
static ActionList_t a_stQc6            = { 2, { &a_stQc6_0, &a_stQc6_1 } };
static short        n_stQc6[]          = { 15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,16,15,15,15,15,15,15,15,15,15,15,15,15};
static CState_t     stQc6              = { 15, "stQc6", 45, n_stQc6, &a_stQc6 };  // [15] 
 
static ActionList_t a_stQc6b           = {  0,  { 0 } };
static short        n_stQc6b[]         = { 16,16,16,16,16,17,16,16,16,16,18,16,16,16,16,17,16,16,16,16,18,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16};
static CState_t     stQc6b             = { 16, "stQc6b", 45, n_stQc6b, &a_stQc6b };  // [16] 
 
static csmAction_t  a_stQc7_0          = { LED, "G!" };
static csmAction_t  a_stQc7_1          = { playRec, "" };
static ActionList_t a_stQc7            = { 2, { &a_stQc7_0, &a_stQc7_1 } };
static short        n_stQc7[]          = { 17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,19,17,17,17,17,17,17,17,17,17,17,17,17};
static CState_t     stQc7              = { 17, "stQc7", 45, n_stQc7, &a_stQc7 };  // [17] 
 
static csmAction_t  a_stQcErrNoTr_0    = { writeMsg, "no_Tree" };
static csmAction_t  a_stQcErrNoTr_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoTr_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoTr      = { 3, { &a_stQcErrNoTr_0, &a_stQcErrNoTr_1, &a_stQcErrNoTr_2 } };
static short        n_stQcErrNoTr[]    = { 18, 2,18,18,18,18,18,18, 3, 1, 0,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18,18};
static CState_t     stQcErrNoTr        = { 18, "stQcErrNoTr", 45, n_stQcErrNoTr, &a_stQcErrNoTr };  // [18] 
 
static csmAction_t  a_stQc7b_0         = { LED, "_" };
static csmAction_t  a_stQc7b_1         = { playTune, "G/" };
static ActionList_t a_stQc7b           = { 2, { &a_stQc7b_0, &a_stQc7b_1 } };
static short        n_stQc7b[]         = { 19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,20,19,19,19,19,19,19,19,19,19,19,19,19};
static CState_t     stQc7b             = { 19, "stQc7b", 45, n_stQc7b, &a_stQc7b };  // [19] 
 
static ActionList_t a_stQc8            = {  0,  { 0 } };
static short        n_stQc8[]          = { 20, 7,21, 7, 7, 7, 7, 7, 7, 7,22, 7,21, 7, 7, 7, 7, 7, 7, 7,22, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,20,20,20,20,20,20,20,20,20,20,20,20,20,20};
static CState_t     stQc8              = { 20, "stQc8", 45, n_stQc8, &a_stQc8 };  // [20] 
 
static csmAction_t  a_stQc9_0          = { LED, "G3" };
static csmAction_t  a_stQc9_1          = { playTune, "A/A/" };
static ActionList_t a_stQc9            = { 2, { &a_stQc9_0, &a_stQc9_1 } };
static short        n_stQc9[]          = { 21, 7, 7, 7, 7, 7,23, 7, 7, 7,24, 7, 7, 7, 7, 7,23, 7, 7, 7,24, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,21,21,21,21,21,21,21,21,21,21,21,21,21,21};
static CState_t     stQc9              = { 21, "stQc9", 45, n_stQc9, &a_stQc9 };  // [21] 
 
static csmAction_t  a_stQcErrPlay_0    = { writeMsg, "rec_Play" };
static csmAction_t  a_stQcErrPlay_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrPlay_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrPlay      = { 3, { &a_stQcErrPlay_0, &a_stQcErrPlay_1, &a_stQcErrPlay_2 } };
static short        n_stQcErrPlay[]    = { 22, 2,22,22,22,22,22,22, 3, 1, 0,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22};
static CState_t     stQcErrPlay        = { 22, "stQcErrPlay", 45, n_stQcErrPlay, &a_stQcErrPlay };  // [22] 
 
static csmAction_t  a_stQc10_0         = { LED, "G3" };
static csmAction_t  a_stQc10_1         = { playTune, "G/" };
static ActionList_t a_stQc10           = { 2, { &a_stQc10_0, &a_stQc10_1 } };
static short        n_stQc10[]         = { 23, 7, 7, 7, 7, 7, 7, 7,25, 7,26, 7, 7, 7, 7, 7, 7, 7,25, 7,26, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,23,23,23,23,23,23,23,23,23,23,23,23,23,23};
static CState_t     stQc10             = { 23, "stQc10", 45, n_stQc10, &a_stQc10 };  // [23] 
 
static csmAction_t  a_stQcErrNoLh_0    = { writeMsg, "no_Lhand" };
static csmAction_t  a_stQcErrNoLh_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoLh_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoLh      = { 3, { &a_stQcErrNoLh_0, &a_stQcErrNoLh_1, &a_stQcErrNoLh_2 } };
static short        n_stQcErrNoLh[]    = { 24, 2,24,24,24,24,24,24, 3, 1, 0,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24};
static CState_t     stQcErrNoLh        = { 24, "stQcErrNoLh", 45, n_stQcErrNoLh, &a_stQcErrNoLh };  // [24] 
 
static csmAction_t  a_stQc11_0         = { LED, "G3" };
static csmAction_t  a_stQc11_1         = { playTune, "F/" };
static ActionList_t a_stQc11           = { 2, { &a_stQc11_0, &a_stQc11_1 } };
static short        n_stQc11[]         = { 25, 7, 7, 7, 7, 7, 7,27, 7, 7,28, 7, 7, 7, 7, 7, 7,27, 7, 7,28, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,25,25,25,25,25,25,25,25,25,25,25,25,25,25};
static CState_t     stQc11             = { 25, "stQc11", 45, n_stQc11, &a_stQc11 };  // [25] 
 
static csmAction_t  a_stQcErrNoPo_0    = { writeMsg, "no_Pot" };
static csmAction_t  a_stQcErrNoPo_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoPo_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoPo      = { 3, { &a_stQcErrNoPo_0, &a_stQcErrNoPo_1, &a_stQcErrNoPo_2 } };
static short        n_stQcErrNoPo[]    = { 26, 2,26,26,26,26,26,26, 3, 1, 0,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26};
static CState_t     stQcErrNoPo        = { 26, "stQcErrNoPo", 45, n_stQcErrNoPo, &a_stQcErrNoPo };  // [26] 
 
static csmAction_t  a_stQc12_0         = { LED, "G3" };
static csmAction_t  a_stQc12_1         = { playTune, "E/" };
static ActionList_t a_stQc12           = { 2, { &a_stQc12_0, &a_stQc12_1 } };
static short        n_stQc12[]         = { 27, 7, 7, 7, 7, 7, 7, 7, 7,29,30, 7, 7, 7, 7, 7, 7, 7, 7,29,30, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,27,27,27,27,27,27,27,27,27,27,27,27,27,27};
static CState_t     stQc12             = { 27, "stQc12", 45, n_stQc12, &a_stQc12 };  // [27] 
 
static csmAction_t  a_stQcErrNoRh_0    = { writeMsg, "no_Rhand" };
static csmAction_t  a_stQcErrNoRh_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoRh_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoRh      = { 3, { &a_stQcErrNoRh_0, &a_stQcErrNoRh_1, &a_stQcErrNoRh_2 } };
static short        n_stQcErrNoRh[]    = { 28, 2,28,28,28,28,28,28, 3, 1, 0,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28};
static CState_t     stQcErrNoRh        = { 28, "stQcErrNoRh", 45, n_stQcErrNoRh, &a_stQcErrNoRh };  // [28] 
 
static csmAction_t  a_stQc13_0         = { LED, "G3" };
static csmAction_t  a_stQc13_1         = { playTune, "D/" };
static ActionList_t a_stQc13           = { 2, { &a_stQc13_0, &a_stQc13_1 } };
static short        n_stQc13[]         = { 29, 7, 7, 7, 7, 7, 7, 7, 7,32,31, 7, 7, 7, 7, 7, 7, 7, 7,32,31, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,29,29,29,29,29,29,29,29,29,29,29,29,29,29};
static CState_t     stQc13             = { 29, "stQc13", 45, n_stQc13, &a_stQc13 };  // [29] 
 
static csmAction_t  a_stQcErrNoSt_0    = { writeMsg, "no_Star" };
static csmAction_t  a_stQcErrNoSt_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoSt_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoSt      = { 3, { &a_stQcErrNoSt_0, &a_stQcErrNoSt_1, &a_stQcErrNoSt_2 } };
static short        n_stQcErrNoSt[]    = { 30, 2,30,30,30,30,30,30, 3, 1, 0,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30};
static CState_t     stQcErrNoSt        = { 30, "stQcErrNoSt", 45, n_stQcErrNoSt, &a_stQcErrNoSt };  // [30] 
 
static csmAction_t  a_stQc14_0         = { playTune, "C/C*" };
static ActionList_t a_stQc14           = { 1, { &a_stQc14_0 } };
static short        n_stQc14[]         = { 31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,33,31,31,31,31,31,31,31,31,31,31,31,31};
static CState_t     stQc14             = { 31, "stQc14", 45, n_stQc14, &a_stQc14 };  // [31] 
 
static csmAction_t  a_stQcErrNoTa_0    = { writeMsg, "no_Table" };
static csmAction_t  a_stQcErrNoTa_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoTa_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoTa      = { 3, { &a_stQcErrNoTa_0, &a_stQcErrNoTa_1, &a_stQcErrNoTa_2 } };
static short        n_stQcErrNoTa[]    = { 32, 2,32,32,32,32,32,32, 3, 1, 0,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32};
static CState_t     stQcErrNoTa        = { 32, "stQcErrNoTa", 45, n_stQcErrNoTa, &a_stQcErrNoTa };  // [32] 
 
static csmAction_t  a_stQc15_0         = { writeMsg, "QC_OK" };
static csmAction_t  a_stQc15_1         = { bgLED, "G2_8" };
static ActionList_t a_stQc15           = { 2, { &a_stQc15_0, &a_stQc15_1 } };
static short        n_stQc15[]         = { 33, 2,33,33,33,33,33,33, 3, 1, 0,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33,33};
static CState_t     stQc15             = { 33, "stQc15", 45, n_stQc15, &a_stQc15 };  // [33] 
 
static csmAction_t  a_stQcSkip2_0      = { writeMsg, "QC_OK_short" };
static csmAction_t  a_stQcSkip2_1      = { bgLED, "G2_8" };
static ActionList_t a_stQcSkip2        = { 2, { &a_stQcSkip2_0, &a_stQcSkip2_1 } };
static short        n_stQcSkip2[]      = { 34, 2,34,34,34,34,34,34, 3, 1, 0,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34,34};
static CState_t     stQcSkip2          = { 34, "stQcSkip2", 45, n_stQcSkip2, &a_stQcSkip2 };  // [34] 
 
static CSList_t  preCSlist = {  35, 
  {
          &stQcTest,           &stQcUSB,        &stQcReboot,       &stQcSysTest,             &stQc1,
             &stQc2,      &stQcErrFiles,          &stQcBeep,             &stQc3,        &stQcErrGrn,
             &stQc4,        &stQcErrRed,             &stQc5,       &stQcErrNoMi,          &stQcSkip,
             &stQc6,            &stQc6b,             &stQc7,       &stQcErrNoTr,            &stQc7b,
             &stQc8,             &stQc9,       &stQcErrPlay,            &stQc10,       &stQcErrNoLh,
            &stQc11,       &stQcErrNoPo,            &stQc12,       &stQcErrNoRh,            &stQc13,
       &stQcErrNoSt,            &stQc14,       &stQcErrNoTa,            &stQc15,         &stQcSkip2,

  }
};  
static CSM_t preCSM = { 
    "// TB CSM 2021-10-12: vPRE QC_preload version ", 
    &preTB_Config, preSysAudio, &preCSlist
};  // preCSM
 
void     preloadCSM( void ){
    CSM = &preCSM;
    TB_Config = &preTB_Config;
}  // preloadCSM()
 
// preloadCSM.c 
