// preloaded TBook Control State Machine   preloadCSM.c
// generated by org.amplio.CSMcompile version: 8(2021-10-15)
// run at 2022-05-09 08:12:05
// from C:\Users\bill\workspace\CSMcompile\..\tbv2\TbFiles\SDCard\system\control_def.txt of: 2022-05-09 08:12:03
#include "packageData.h" 
//Ver:   // TB CSM 2022-04-27: V20 One touch recording
static TBConfig_t  preTB_Config = { 
  4,  // default_volume 
  180000,  // powerCheckMS 
  5000,  // shortIdleMS 
  180000,  // longIdleMS 
  50,  // minShortPressMS 
  1000,  // minLongPressMS 
  0, // qcTestState 
  1, // initState 
  "system/audio",  // systemAudio 
  "_49G",  // bgPulse 
  "G!",  // fgPlaying 
  "G2_3!",  // fgPlayPaused 
  "R!",  // fgRecording 
  "R2_3!",  // fgRecordPaused 
  "O!",  // fgSavingRec 
  "G3_3G3",  // fgSaveRec 
  "R3_3R3",  // fgCancelRec 
  "O5o5!",  // fgUSB_MSC 
  "R8_2R8_2R8_20!",  // fgTB_Error 
  "_3R3_3R3_3R3_5!",  // fgNoUSBcable 
  "G5g5!",  // fgUSBconnect 
  "G_3G_3G_9G_3G_9G_3",  // fgPowerDown 
};  // preTB_Config
 
static AudioList_t preSysAudio[] = { 
9,  // # PlaySys prompts used by CSM 
{ 
"10",
"11",
"41",
"9",
"1",
"1",
"3",
"0",
"0",
} 
};  // preSysAudio 
 
static csmAction_t  a_stQcTest_0       = { playTune, "C/" };
static ActionList_t a_stQcTest         = { 1, { &a_stQcTest_0 } };
static short        n_stQcTest[]       = {  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static CState_t     stQcTest           = { 0, "stQcTest", 49, n_stQcTest, &a_stQcTest };  // [0] 
 
static csmAction_t  a_stWakeup_0       = { LED, "_" };
static csmAction_t  a_stWakeup_1       = { bgLED, "bgPulse" };
static csmAction_t  a_stWakeup_2       = { changePkg, "" };
static csmAction_t  a_stWakeup_3       = { playSys, "10" };
static ActionList_t a_stWakeup         = { 4, { &a_stWakeup_0, &a_stWakeup_1, &a_stWakeup_2, &a_stWakeup_3 } };
static short        n_stWakeup[]       = {  1, 1, 1,13,14,21,19,20,15,25,23, 2, 1, 1, 1,22,16,17, 1, 1, 1, 1, 1,11, 1, 1, 1, 1, 1, 1, 1,44,24,24, 3, 8, 4, 7,10, 6, 1, 1, 1, 1, 1, 1, 1, 5, 9};
static CState_t     stWakeup           = { 1, "stWakeup", 49, n_stWakeup, &a_stWakeup };  // [1] 
 
static csmAction_t  a_stGoSleep_0      = { playTune, "H/+" };
static csmAction_t  a_stGoSleep_1      = { bgLED, "R" };
static csmAction_t  a_stGoSleep_2      = { setTimer, "1000" };
static ActionList_t a_stGoSleep        = { 3, { &a_stGoSleep_0, &a_stGoSleep_1, &a_stGoSleep_2 } };
static short        n_stGoSleep[]      = {  2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,48, 2, 2, 2, 2, 2, 2, 2};
static CState_t     stGoSleep          = { 2, "stGoSleep", 49, n_stGoSleep, &a_stGoSleep };  // [2] 
 
static csmAction_t  a_stSleepy_0       = { bgLED, "O_9" };
static csmAction_t  a_stSleepy_1       = { saveSt, "1" };
static csmAction_t  a_stSleepy_2       = { setTimer, "5000" };
static ActionList_t a_stSleepy         = { 3, { &a_stSleepy_0, &a_stSleepy_1, &a_stSleepy_2 } };
static short        n_stSleepy[]       = {  3, 1,47,47,47,47,47,47,47,47,47, 2,47,47,47,47,47,47,47,47,47,47,47,11,47,47,47,47,47,47,47, 3, 3, 3, 3, 8, 4, 7,10, 6, 3, 2, 3, 3, 3, 3, 3, 5, 9};
static CState_t     stSleepy           = { 3, "stSleepy", 49, n_stSleepy, &a_stSleepy };  // [3] 
 
static csmAction_t  a_stOnCharging_0   = { bgLED, "R_49" };
static csmAction_t  a_stOnCharging_1   = { goPrevSt, "" };
static ActionList_t a_stOnCharging     = { 2, { &a_stOnCharging_0, &a_stOnCharging_1 } };
static short        n_stOnCharging[]   = {  4, 1, 4,36,37, 4, 4, 4, 4, 4, 4, 2,39, 4, 4, 4, 4, 4, 4, 4, 4, 4,40,11,38, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 8, 4, 7,10, 6, 4, 4, 4, 4, 4, 4, 4, 5, 9};
static CState_t     stOnCharging       = { 4, "stOnCharging", 49, n_stOnCharging, &a_stOnCharging };  // [4] 
 
static csmAction_t  a_stOnCharging75_0 = { bgLED, "G_49" };
static csmAction_t  a_stOnCharging75_1 = { goPrevSt, "" };
static ActionList_t a_stOnCharging75   = { 2, { &a_stOnCharging75_0, &a_stOnCharging75_1 } };
static short        n_stOnCharging75[] = {  5, 1, 5,36,37, 5, 5, 5, 5, 5, 5, 2,39, 5, 5, 5, 5, 5, 5, 5, 5, 5,40,11,38, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 8, 4, 7,10, 6, 5, 5, 5, 5, 5, 5, 5, 5, 9};
static CState_t     stOnCharging75     = { 5, "stOnCharging75", 49, n_stOnCharging75, &a_stOnCharging75 };  // [5] 
 
static csmAction_t  a_stNearCharged_0  = { bgLED, "G_G_47" };
static csmAction_t  a_stNearCharged_1  = { goPrevSt, "" };
static ActionList_t a_stNearCharged    = { 2, { &a_stNearCharged_0, &a_stNearCharged_1 } };
static short        n_stNearCharged[]  = {  6, 1, 6,36,37, 6, 6, 6, 6, 6, 6, 2,39, 6, 6, 6, 6, 6, 6, 6, 6, 6,40,11,38, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 8, 4, 7,10, 6, 6, 6, 6, 6, 6, 6, 6, 5, 9};
static CState_t     stNearCharged      = { 6, "stNearCharged", 49, n_stNearCharged, &a_stNearCharged };  // [6] 
 
static csmAction_t  a_stOnCharged_0    = { bgLED, "_" };
static csmAction_t  a_stOnCharged_1    = { goPrevSt, "" };
static ActionList_t a_stOnCharged      = { 2, { &a_stOnCharged_0, &a_stOnCharged_1 } };
static short        n_stOnCharged[]    = {  7, 1, 7,36,37, 7, 7, 7, 7, 7, 7, 2,39, 7, 7, 7, 7, 7, 7, 7, 7, 7,40,11,38, 7, 7, 7, 7, 7, 7, 7, 7, 7, 3, 8, 4, 7,10, 6, 7, 7, 7, 7, 7, 7, 7, 5, 9};
static CState_t     stOnCharged        = { 7, "stOnCharged", 49, n_stOnCharged, &a_stOnCharged };  // [7] 
 
static csmAction_t  a_stOnLowBatt_0    = { bgLED, "R_19" };
static csmAction_t  a_stOnLowBatt_1    = { goPrevSt, "" };
static ActionList_t a_stOnLowBatt      = { 2, { &a_stOnLowBatt_0, &a_stOnLowBatt_1 } };
static short        n_stOnLowBatt[]    = {  8, 1, 8,36,37,21,19,20, 8,25,23, 2,39, 8, 8,22, 8, 8, 8, 8, 8, 8,40,11,38, 8, 8, 8, 8, 8, 8, 8,24,24, 3, 8, 4, 7,10, 6, 8, 8, 8, 8, 8, 8, 8, 5, 9};
static CState_t     stOnLowBatt        = { 8, "stOnLowBatt", 49, n_stOnLowBatt, &a_stOnLowBatt };  // [8] 
 
static csmAction_t  a_stNotCharging_0  = { bgLED, "_" };
static csmAction_t  a_stNotCharging_1  = { goPrevSt, "" };
static ActionList_t a_stNotCharging    = { 2, { &a_stNotCharging_0, &a_stNotCharging_1 } };
static short        n_stNotCharging[]  = {  9, 1, 9,36,37,21,19,20, 9,25,23, 2,39, 9, 9,22, 9, 9, 9, 9, 9, 9,40,11,38, 9, 9, 9, 9, 9, 9, 9,24,24, 3, 8, 4, 7,10, 6, 9, 9, 9, 9, 9, 9, 9, 5, 9};
static CState_t     stNotCharging      = { 9, "stNotCharging", 49, n_stNotCharging, &a_stNotCharging };  // [9] 
 
static csmAction_t  a_stOnBattMin_0    = { bgLED, "R20_30" };
static csmAction_t  a_stOnBattMin_1    = { setTimer, "5000" };
static ActionList_t a_stOnBattMin      = { 2, { &a_stOnBattMin_0, &a_stOnBattMin_1 } };
static short        n_stOnBattMin[]    = { 10, 1, 1,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,48,10,10,10,10,10,10,10};
static CState_t     stOnBattMin        = { 10, "stOnBattMin", 49, n_stOnBattMin, &a_stOnBattMin };  // [10] 
 
static csmAction_t  a_stUSBmode_0      = { bgLED, "R2_8G2_8" };
static csmAction_t  a_stUSBmode_1      = { startUSB, "" };
static ActionList_t a_stUSBmode        = { 2, { &a_stUSBmode_0, &a_stUSBmode_1 } };
static short        n_stUSBmode[]      = { 11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,12,11,11,11,11,11,11,11,11,11,11,11, 8, 4, 7,10, 6,11,11,11,11,11,11,11,11,11};
static CState_t     stUSBmode          = { 11, "stUSBmode", 49, n_stUSBmode, &a_stUSBmode };  // [11] 
 
static csmAction_t  a_stCloseUSB_0     = { endUSB, "" };
static csmAction_t  a_stCloseUSB_1     = { bgLED, "G_29" };
static csmAction_t  a_stCloseUSB_2     = { setTimer, "1000" };
static ActionList_t a_stCloseUSB       = { 3, { &a_stCloseUSB_0, &a_stCloseUSB_1, &a_stCloseUSB_2 } };
static short        n_stCloseUSB[]     = { 12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12,12, 1,12,12,12,12,12,12,12};
static CState_t     stCloseUSB         = { 12, "stCloseUSB", 49, n_stCloseUSB, &a_stCloseUSB };  // [12] 
 
static csmAction_t  a_stPlayLouder_0   = { volAdj, "1" };
static csmAction_t  a_stPlayLouder_1   = { goPrevSt, "" };
static ActionList_t a_stPlayLouder     = { 2, { &a_stPlayLouder_0, &a_stPlayLouder_1 } };
static short        n_stPlayLouder[]   = { 13, 1,13,13,14,13,13,13,15,13,13, 2,13,13,13,13,16,17,13,13,13,13,13,11,13,13,13,13,13,13,13,13,13,13, 3, 8, 4, 7,10, 6,13,13,13,13,13,13,13, 5, 9};
static CState_t     stPlayLouder       = { 13, "stPlayLouder", 49, n_stPlayLouder, &a_stPlayLouder };  // [13] 
 
static csmAction_t  a_stPlaySofter_0   = { volAdj, "-1" };
static csmAction_t  a_stPlaySofter_1   = { goPrevSt, "" };
static ActionList_t a_stPlaySofter     = { 2, { &a_stPlaySofter_0, &a_stPlaySofter_1 } };
static short        n_stPlaySofter[]   = { 14, 1,14,13,14,14,14,14,15,14,14, 2,14,14,14,14,16,17,14,14,14,14,14,11,14,14,14,14,14,14,14,14,14,14, 3, 8, 4, 7,10, 6,14,14,14,14,14,14,14, 5, 9};
static CState_t     stPlaySofter       = { 14, "stPlaySofter", 49, n_stPlaySofter, &a_stPlaySofter };  // [14] 
 
static csmAction_t  a_stPlayPause_0    = { saveSt, "2" };
static csmAction_t  a_stPlayPause_1    = { setTimer, "8000" };
static csmAction_t  a_stPlayPause_2    = { pausePlay, "" };
static ActionList_t a_stPlayPause      = { 3, { &a_stPlayPause_0, &a_stPlayPause_1, &a_stPlayPause_2 } };
static short        n_stPlayPause[]    = { 15, 1,15,13,14,21,19,20,18,25,23, 2,15,15,15,22,16,17,15,15,15,15,15,11,15,15,15,15,15,15,15,15,24,24, 3, 8, 4, 7,10, 6,15, 2,15,15,15,15,15, 5, 9};
static CState_t     stPlayPause        = { 15, "stPlayPause", 49, n_stPlayPause, &a_stPlayPause };  // [15] 
 
static csmAction_t  a_stPlayJumpBack_0 = { posAdj, "-7" };
static csmAction_t  a_stPlayJumpBack_1 = { goPrevSt, "" };
static ActionList_t a_stPlayJumpBack   = { 2, { &a_stPlayJumpBack_0, &a_stPlayJumpBack_1 } };
static short        n_stPlayJumpBack[] = { 16, 1,16,13,14,21,19,20,15,25,23, 2,16,16,16,22,16,17,16,16,16,16,16,11,16,16,16,16,16,16,16,16,24,24, 3, 8, 4, 7,10, 6,16,16,16,16,16,16,16, 5, 9};
static CState_t     stPlayJumpBack     = { 16, "stPlayJumpBack", 49, n_stPlayJumpBack, &a_stPlayJumpBack };  // [16] 
 
static csmAction_t  a_stPlayJumpFwd_0  = { posAdj, "60" };
static csmAction_t  a_stPlayJumpFwd_1  = { goPrevSt, "" };
static ActionList_t a_stPlayJumpFwd    = { 2, { &a_stPlayJumpFwd_0, &a_stPlayJumpFwd_1 } };
static short        n_stPlayJumpFwd[]  = { 17, 1,17,13,14,21,19,20,15,25,23, 2,17,17,17,22,16,17,17,17,17,17,17,11,17,17,17,17,17,17,17,17,24,24, 3, 8, 4, 7,10, 6,17,17,17,17,17,17,17, 5, 9};
static CState_t     stPlayJumpFwd      = { 17, "stPlayJumpFwd", 49, n_stPlayJumpFwd, &a_stPlayJumpFwd };  // [17] 
 
static csmAction_t  a_stPlayResume_0   = { resumePlay, "" };
static csmAction_t  a_stPlayResume_1   = { goSavedSt, "2" };
static ActionList_t a_stPlayResume     = { 2, { &a_stPlayResume_0, &a_stPlayResume_1 } };
static short        n_stPlayResume[]   = { 18, 1,18,13,14,21,19,20,15,25,23, 2,18,18,18,22,16,17,18,18,18,18,18,11,18,18,18,18,18,18,18,18,24,24, 3, 8, 4, 7,10, 6,18,18,18,18,18,18,18, 5, 9};
static CState_t     stPlayResume       = { 18, "stPlayResume", 49, n_stPlayResume, &a_stPlayResume };  // [18] 
 
static csmAction_t  a_stOnPrevSubj_0   = { subjAdj, "-1" };
static csmAction_t  a_stOnPrevSubj_1   = { playSubj, "nm" };
static ActionList_t a_stOnPrevSubj     = { 2, { &a_stOnPrevSubj_0, &a_stOnPrevSubj_1 } };
static short        n_stOnPrevSubj[]   = { 19, 1,19,13,14,21,19,20,15,25,23, 2,19,19,19,22,16,17,19,19,19,19,19,11,19,19,19,19,19,19,19,49,24,24, 3, 8, 4, 7,10, 6,19,19,19,19,19,19,19, 5, 9};
static CState_t     stOnPrevSubj       = { 19, "stOnPrevSubj", 49, n_stOnPrevSubj, &a_stOnPrevSubj };  // [19] 
 
static csmAction_t  a_stOnNextSubj_0   = { subjAdj, "1" };
static csmAction_t  a_stOnNextSubj_1   = { playSubj, "nm" };
static ActionList_t a_stOnNextSubj     = { 2, { &a_stOnNextSubj_0, &a_stOnNextSubj_1 } };
static short        n_stOnNextSubj[]   = { 20, 1,20,13,14,21,19,20,15,25,23, 2,20,20,20,22,16,17,20,20,20,20,20,11,20,20,20,20,20,20,20,49,24,24, 3, 8, 4, 7,10, 6,20,20,20,20,20,20,20, 5, 9};
static CState_t     stOnNextSubj       = { 20, "stOnNextSubj", 49, n_stOnNextSubj, &a_stOnNextSubj };  // [20] 
 
static csmAction_t  a_stOnNextMsg_0    = { msgAdj, "1" };
static csmAction_t  a_stOnNextMsg_1    = { playSubj, "msg" };
static ActionList_t a_stOnNextMsg      = { 2, { &a_stOnNextMsg_0, &a_stOnNextMsg_1 } };
static short        n_stOnNextMsg[]    = { 21, 1,21,13,14,21,19,20,15,25,23, 2,21,21,21,22,16,17,21,21,21,21,21,11,21,21,21,21,21,21,21,52,24,24, 3, 8, 4, 7,10, 6,21,21,21,21,21,21,21, 5, 9};
static CState_t     stOnNextMsg        = { 21, "stOnNextMsg", 49, n_stOnNextMsg, &a_stOnNextMsg };  // [21] 
 
static csmAction_t  a_stOnRepeatMsg_0  = { msgAdj, "1" };
static csmAction_t  a_stOnRepeatMsg_1  = { playSubj, "msg" };
static ActionList_t a_stOnRepeatMsg    = { 2, { &a_stOnRepeatMsg_0, &a_stOnRepeatMsg_1 } };
static short        n_stOnRepeatMsg[]  = { 22, 1,22,13,14,21,19,20,15,25,23, 2,22,22,22,22,16,17,22,22,22,22,22,11,22,22,22,22,22,22,22,54,24,24, 3, 8, 4, 7,10, 6,22,22,22,22,22,22,22, 5, 9};
static CState_t     stOnRepeatMsg      = { 22, "stOnRepeatMsg", 49, n_stOnRepeatMsg, &a_stOnRepeatMsg };  // [22] 
 
static csmAction_t  a_stOnPrevMsg_0    = { msgAdj, "-1" };
static csmAction_t  a_stOnPrevMsg_1    = { playSubj, "msg" };
static ActionList_t a_stOnPrevMsg      = { 2, { &a_stOnPrevMsg_0, &a_stOnPrevMsg_1 } };
static short        n_stOnPrevMsg[]    = { 23, 1,23,13,14,21,19,20,15,25,23, 2,23,23,23,22,16,17,23,23,23,23,23,11,23,23,23,23,23,23,23,52,24,24, 3, 8, 4, 7,10, 6,23,23,23,23,23,23,23, 5, 9};
static CState_t     stOnPrevMsg        = { 23, "stOnPrevMsg", 49, n_stOnPrevMsg, &a_stOnPrevMsg };  // [23] 
 
static ActionList_t a_stWait           = {  0,  { 0 } };
static short        n_stWait[]         = { 24, 1,24,36,37,21,19,20,24,25,23, 2,39,24,24,22,24,24,24,24,24,24,40,11,38,24,24,24,24,24,24,24,24,24, 3, 8, 4, 7,10, 6,24,24,24,24,24,24,24, 5, 9};
static CState_t     stWait             = { 24, "stWait", 49, n_stWait, &a_stWait };  // [24] 
 
static csmAction_t  a_stBeginRecording_0 = { saveSt, "2" };
static csmAction_t  a_stBeginRecording_1 = { playSys, "1" };
static ActionList_t a_stBeginRecording = { 2, { &a_stBeginRecording_0, &a_stBeginRecording_1 } };
static short        n_stBeginRecording[] = { 25, 1,25,25,25,25,25,25,26,27,25, 2,25,25,25,25,25,25,25,25,25,25,25,11,25,25,25,25,25,25,25,25,55,25, 3, 8, 4, 7,10, 6,25,25,25,25,25,25,25, 5, 9};
static CState_t     stBeginRecording   = { 25, "stBeginRecording", 49, n_stBeginRecording, &a_stBeginRecording };  // [25] 
 
static csmAction_t  a_stRecordingPaused_0 = { saveSt, "3" };
static csmAction_t  a_stRecordingPaused_1 = { pauseRec, "" };
static ActionList_t a_stRecordingPaused = { 2, { &a_stRecordingPaused_0, &a_stRecordingPaused_1 } };
static short        n_stRecordingPaused[] = { 26, 1,26,26,26,26,26,26,28,26,26, 2,26,26,26,26,26,26,26,26,26,26,26,11,26,26,26,26,26,26,26,26,26,26, 3, 8, 4, 7,10, 6,26,26,26,26,26,26,26, 5, 9};
static CState_t     stRecordingPaused  = { 26, "stRecordingPaused", 49, n_stRecordingPaused, &a_stRecordingPaused };  // [26] 
 
static csmAction_t  a_stRecordingDone_0 = { finishRec, "" };
static csmAction_t  a_stRecordingDone_1 = { playSys, "3" };
static ActionList_t a_stRecordingDone  = { 2, { &a_stRecordingDone_0, &a_stRecordingDone_1 } };
static short        n_stRecordingDone[] = { 27, 1,27,27,27,27,27,27,27,27,27, 2,27,27,27,27,27,27,27,27,27,27,27,11,27,27,27,27,27,27,27,27,56,27, 3, 8, 4, 7,10, 6,27,27,27,27,27,27,27, 5, 9};
static CState_t     stRecordingDone    = { 27, "stRecordingDone", 49, n_stRecordingDone, &a_stRecordingDone };  // [27] 
 
static csmAction_t  a_stRecordingResumed_0 = { resumeRec, "" };
static csmAction_t  a_stRecordingResumed_1 = { goSavedSt, "3" };
static ActionList_t a_stRecordingResumed = { 2, { &a_stRecordingResumed_0, &a_stRecordingResumed_1 } };
static short        n_stRecordingResumed[] = { 28, 1,28,28,28,28,28,28,26,27,28, 2,28,28,28,28,28,28,28,28,28,28,28,11,28,28,28,28,28,28,28,28,28,28, 3, 8, 4, 7,10, 6,28,28,28,28,28,28,28, 5, 9};
static CState_t     stRecordingResumed = { 28, "stRecordingResumed", 49, n_stRecordingResumed, &a_stRecordingResumed };  // [28] 
 
static csmAction_t  a_stEndRecordingHome_0 = { saveRec, "" };
static csmAction_t  a_stEndRecordingHome_1 = { setTimer, "100" };
static ActionList_t a_stEndRecordingHome = { 2, { &a_stEndRecordingHome_0, &a_stEndRecordingHome_1 } };
static short        n_stEndRecordingHome[] = { 29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29, 1,29,29,29,29,29,29,29};
static CState_t     stEndRecordingHome = { 29, "stEndRecordingHome", 49, n_stEndRecordingHome, &a_stEndRecordingHome };  // [29] 
 
static csmAction_t  a_stRecordAnother_0 = { playSys, "1" };
static ActionList_t a_stRecordAnother  = { 1, { &a_stRecordAnother_0 } };
static short        n_stRecordAnother[] = { 30, 1,30,30,30,30,30,30,26,27,30, 2,30,30,30,30,30,30,30,30,30,30,30,11,30,30,30,30,30,30,30,30,55,30, 3, 8, 4, 7,10, 6,30,30,30,30,30,30,30, 5, 9};
static CState_t     stRecordAnother    = { 30, "stRecordAnother", 49, n_stRecordAnother, &a_stRecordAnother };  // [30] 
 
static csmAction_t  a_stEndRecording_0 = { saveRec, "" };
static csmAction_t  a_stEndRecording_1 = { LED, "_" };
static csmAction_t  a_stEndRecording_2 = { goSavedSt, "2" };
static ActionList_t a_stEndRecording   = { 3, { &a_stEndRecording_0, &a_stEndRecording_1, &a_stEndRecording_2 } };
static short        n_stEndRecording[] = { 31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31};
static CState_t     stEndRecording     = { 31, "stEndRecording", 49, n_stEndRecording, &a_stEndRecording };  // [31] 
 
static csmAction_t  a_stReviewPaused_0 = { saveSt, "3" };
static csmAction_t  a_stReviewPaused_1 = { pausePlay, "" };
static ActionList_t a_stReviewPaused   = { 2, { &a_stReviewPaused_0, &a_stReviewPaused_1 } };
static short        n_stReviewPaused[] = { 32,29,31,32,32,31,31,31,35,30,31, 2,32,32,32,32,32,32,32,32,32,32,32,11,32,32,32,32,32,32,32,32,32,32, 3, 8, 4, 7,10, 6,32,32,32,32,32,32,32, 5, 9};
static CState_t     stReviewPaused     = { 32, "stReviewPaused", 49, n_stReviewPaused, &a_stReviewPaused };  // [32] 
 
static csmAction_t  a_stReviewLouder_0 = { volAdj, "1" };
static csmAction_t  a_stReviewLouder_1 = { goPrevSt, "" };
static ActionList_t a_stReviewLouder   = { 2, { &a_stReviewLouder_0, &a_stReviewLouder_1 } };
static short        n_stReviewLouder[] = { 33,29,31,33,34,31,31,31,32,30,31, 2,33,33,33,33,33,33,33,33,33,33,33,11,33,33,33,33,33,33,33,33,33,33, 3, 8, 4, 7,10, 6,33,33,33,33,33,33,33, 5, 9};
static CState_t     stReviewLouder     = { 33, "stReviewLouder", 49, n_stReviewLouder, &a_stReviewLouder };  // [33] 
 
static csmAction_t  a_stReviewSofter_0 = { volAdj, "-1" };
static csmAction_t  a_stReviewSofter_1 = { goPrevSt, "" };
static ActionList_t a_stReviewSofter   = { 2, { &a_stReviewSofter_0, &a_stReviewSofter_1 } };
static short        n_stReviewSofter[] = { 34,29,31,33,34,31,31,31,32,30,31, 2,34,34,34,34,34,34,34,34,34,34,34,11,34,34,34,34,34,34,34,34,34,34, 3, 8, 4, 7,10, 6,34,34,34,34,34,34,34, 5, 9};
static CState_t     stReviewSofter     = { 34, "stReviewSofter", 49, n_stReviewSofter, &a_stReviewSofter };  // [34] 
 
static csmAction_t  a_stReviewResumed_0 = { resumePlay, "" };
static csmAction_t  a_stReviewResumed_1 = { goSavedSt, "3" };
static ActionList_t a_stReviewResumed  = { 2, { &a_stReviewResumed_0, &a_stReviewResumed_1 } };
static short        n_stReviewResumed[] = { 35,29,31,33,34,31,31,31,32,30,31, 2,35,35,35,35,35,35,35,35,35,35,35,11,35,35,35,35,35,35,35,35,35,35, 3, 8, 4, 7,10, 6,35,35,35,35,35,35,35, 5, 9};
static CState_t     stReviewResumed    = { 35, "stReviewResumed", 49, n_stReviewResumed, &a_stReviewResumed };  // [35] 
 
static csmAction_t  a_stIdleLouder_0   = { volAdj, "1" };
static csmAction_t  a_stIdleLouder_1   = { playSys, "0" };
static csmAction_t  a_stIdleLouder_2   = { goPrevSt, "" };
static ActionList_t a_stIdleLouder     = { 3, { &a_stIdleLouder_0, &a_stIdleLouder_1, &a_stIdleLouder_2 } };
static short        n_stIdleLouder[]   = { 36, 1,36,13,14,36,36,36,15,36,36, 2,36,36,36,36,16,17,36,36,36,36,36,11,36,36,36,36,36,36,36,36,36,36, 3, 8, 4, 7,10, 6,36,36,36,36,36,36,36, 5, 9};
static CState_t     stIdleLouder       = { 36, "stIdleLouder", 49, n_stIdleLouder, &a_stIdleLouder };  // [36] 
 
static csmAction_t  a_stIdleSofter_0   = { volAdj, "-1" };
static csmAction_t  a_stIdleSofter_1   = { playSys, "0" };
static csmAction_t  a_stIdleSofter_2   = { goPrevSt, "" };
static ActionList_t a_stIdleSofter     = { 3, { &a_stIdleSofter_0, &a_stIdleSofter_1, &a_stIdleSofter_2 } };
static short        n_stIdleSofter[]   = { 37, 1,37,13,14,37,37,37,15,37,37, 2,37,37,37,37,16,17,37,37,37,37,37,11,37,37,37,37,37,37,37,37,37,37, 3, 8, 4, 7,10, 6,37,37,37,37,37,37,37, 5, 9};
static CState_t     stIdleSofter       = { 37, "stIdleSofter", 49, n_stIdleSofter, &a_stIdleSofter };  // [37] 
 
static csmAction_t  a_stShowBatt_0     = { showCharge, "" };
static csmAction_t  a_stShowBatt_1     = { goPrevSt, "" };
static ActionList_t a_stShowBatt       = { 2, { &a_stShowBatt_0, &a_stShowBatt_1 } };
static short        n_stShowBatt[]     = { 38, 1,38,36,37,38,38,38,38,38,38, 2,39,38,38,38,38,38,38,38,38,38,40,11,38,38,38,38,38,38,38,38,38,38, 3, 8, 4, 7,10, 6,38,38,38,38,38,38,38, 5, 9};
static CState_t     stShowBatt         = { 38, "stShowBatt", 49, n_stShowBatt, &a_stShowBatt };  // [38] 
 
static csmAction_t  a_stChgPkg_0       = { changePkg, "" };
static ActionList_t a_stChgPkg         = { 1, { &a_stChgPkg_0 } };
static short        n_stChgPkg[]       = { 39, 1,39,36,37,21,19,20,39,25,23, 2,39,39,39,22,39,39,39,39,39,39,40,11,38,39,39,39,39,39,39,39,24,24, 3, 8, 4, 7,10, 6,39,39,39,39,39,39,39, 5, 9};
static CState_t     stChgPkg           = { 39, "stChgPkg", 49, n_stChgPkg, &a_stChgPkg };  // [39] 
 
static csmAction_t  a_stNxtPkg_0       = { playNxtPkg, "" };
static ActionList_t a_stNxtPkg         = { 1, { &a_stNxtPkg_0 } };
static short        n_stNxtPkg[]       = { 40, 1,40,36,37,40,40,40,40,40,40, 2,39,40,40,40,40,40,40,40,40,40,40,11,38,40,40,40,40,40,40,40,40,40, 3, 8, 4, 7,10, 6,40,40,40,40,40,40,40, 5, 9};
static CState_t     stNxtPkg           = { 40, "stNxtPkg", 49, n_stNxtPkg, &a_stNxtPkg };  // [40] 
 
static csmAction_t  a_stQcUSB_0        = { bgLED, "O2_8" };
static csmAction_t  a_stQcUSB_1        = { startUSB, "" };
static ActionList_t a_stQcUSB          = { 2, { &a_stQcUSB_0, &a_stQcUSB_1 } };
static short        n_stQcUSB[]        = { 41,42,41,41,41,41,41,41,43,41, 0,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41,41};
static CState_t     stQcUSB            = { 41, "stQcUSB", 49, n_stQcUSB, &a_stQcUSB };  // [41] 
 
static csmAction_t  a_stQcReboot_0     = { sysBoot, "" };
static ActionList_t a_stQcReboot       = { 1, { &a_stQcReboot_0 } };
static short        n_stQcReboot[]     = { 42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42};
static CState_t     stQcReboot         = { 42, "stQcReboot", 49, n_stQcReboot, &a_stQcReboot };  // [42] 
 
static csmAction_t  a_stQcSysTest_0    = { playTune, "CG/.FDEH.G/" };
static ActionList_t a_stQcSysTest      = { 1, { &a_stQcSysTest_0 } };
static short        n_stQcSysTest[]    = { 43,42,43,43,43,43,43,43,43,41, 0,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43};
static CState_t     stQcSysTest        = { 43, "stQcSysTest", 49, n_stQcSysTest, &a_stQcSysTest };  // [43] 
 
static ActionList_t a_stWelcoming      = {  0,  { 0 } };
static short        n_stWelcoming[]    = { 44, 1,44,13,14,21,19,20,15,25,23, 2,44,44,44,22,16,17,44,44,44,44,44,11,44,44,44,44,44,44,44,44,45,24, 3, 8, 4, 7,10, 6,44,44,44,44,44,44,44, 5, 9};
static CState_t     stWelcoming        = { 44, "stWelcoming", 49, n_stWelcoming, &a_stWelcoming };  // [44] 
 
static csmAction_t  a_stPromptSubj_0   = { playSys, "11" };
static ActionList_t a_stPromptSubj     = { 1, { &a_stPromptSubj_0 } };
static short        n_stPromptSubj[]   = { 45, 1,45,13,14,21,19,20,15,25,23, 2,45,45,45,22,16,17,45,45,45,45,45,11,45,45,45,45,45,45,45,46,24,24, 3, 8, 4, 7,10, 6,45,45,45,45,45,45,45, 5, 9};
static CState_t     stPromptSubj       = { 45, "stPromptSubj", 49, n_stPromptSubj, &a_stPromptSubj };  // [45] 
 
static ActionList_t a_stPromptingSub   = {  0,  { 0 } };
static short        n_stPromptingSub[] = { 46, 1,46,13,14,21,19,20,15,25,23, 2,46,46,46,22,16,17,46,46,46,46,46,11,46,46,46,46,46,46,46,46,24,24, 3, 8, 4, 7,10, 6,46,46,46,46,46,46,46, 5, 9};
static CState_t     stPromptingSub     = { 46, "stPromptingSub", 49, n_stPromptingSub, &a_stPromptingSub };  // [46] 
 
static csmAction_t  a_stUnSleepy_0     = { bgLED, "bgPulse" };
static csmAction_t  a_stUnSleepy_1     = { goSavedSt, "1" };
static ActionList_t a_stUnSleepy       = { 2, { &a_stUnSleepy_0, &a_stUnSleepy_1 } };
static short        n_stUnSleepy[]     = { 47, 1,47,47,47,47,47,47,47,47,47, 2,47,47,47,47,47,47,47,47,47,47,47,11,47,47,47,47,47,47,47,47,47,47, 3, 8, 4, 7,10, 6,47,47,47,47,47,47,47, 5, 9};
static CState_t     stUnSleepy         = { 47, "stUnSleepy", 49, n_stUnSleepy, &a_stUnSleepy };  // [47] 
 
static csmAction_t  a_stFallAsleep_0   = { powerDown, "" };
static ActionList_t a_stFallAsleep     = { 1, { &a_stFallAsleep_0 } };
static short        n_stFallAsleep[]   = { 48, 1, 1,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48,48};
static CState_t     stFallAsleep       = { 48, "stFallAsleep", 49, n_stFallAsleep, &a_stFallAsleep };  // [48] 
 
static ActionList_t a_stAnnouncing     = {  0,  { 0 } };
static short        n_stAnnouncing[]   = { 49, 1,49,13,14,21,19,20,15,25,23, 2,49,49,49,22,16,17,49,49,49,49,49,11,49,49,49,49,49,49,49,49,50,24, 3, 8, 4, 7,10, 6,49,49,49,49,49,49,49, 5, 9};
static CState_t     stAnnouncing       = { 49, "stAnnouncing", 49, n_stAnnouncing, &a_stAnnouncing };  // [49] 
 
static csmAction_t  a_stInvitation_0   = { playSubj, "pr" };
static ActionList_t a_stInvitation     = { 1, { &a_stInvitation_0 } };
static short        n_stInvitation[]   = { 50, 1,50,13,14,21,19,20,15,25,23, 2,50,50,50,22,16,17,50,50,50,50,50,11,50,50,50,50,50,50,50,50,51,24, 3, 8, 4, 7,10, 6,50,50,50,50,50,50,50, 5, 9};
static CState_t     stInvitation       = { 50, "stInvitation", 49, n_stInvitation, &a_stInvitation };  // [50] 
 
static csmAction_t  a_stPromptNextSubj_0 = { playSys, "41" };
static ActionList_t a_stPromptNextSubj = { 1, { &a_stPromptNextSubj_0 } };
static short        n_stPromptNextSubj[] = { 51, 1,51,13,14,21,19,20,15,25,23, 2,51,51,51,22,16,17,51,51,51,51,51,11,51,51,51,51,51,51,51,51,24,24, 3, 8, 4, 7,10, 6,51,51,51,51,51,51,51, 5, 9};
static CState_t     stPromptNextSubj   = { 51, "stPromptNextSubj", 49, n_stPromptNextSubj, &a_stPromptNextSubj };  // [51] 
 
static ActionList_t a_stPlaying        = {  0,  { 0 } };
static short        n_stPlaying[]      = { 52, 1,52,13,14,21,19,20,15,25,23, 2,52,52,52,22,16,17,52,52,52,52,52,11,52,52,52,52,52,52,52,52,53,24, 3, 8, 4, 7,10, 6,52,52,52,52,52,52,52, 5, 9};
static CState_t     stPlaying          = { 52, "stPlaying", 49, n_stPlaying, &a_stPlaying };  // [52] 
 
static csmAction_t  a_stInterMsg_0     = { playSys, "9" };
static ActionList_t a_stInterMsg       = { 1, { &a_stInterMsg_0 } };
static short        n_stInterMsg[]     = { 53, 1,53,13,14,21,19,20,15,25,23, 2,53,53,53,22,16,17,53,53,53,53,53,11,53,53,53,53,53,53,53,53,24,24, 3, 8, 4, 7,10, 6,53,53,53,53,53,53,53, 5, 9};
static CState_t     stInterMsg         = { 53, "stInterMsg", 49, n_stInterMsg, &a_stInterMsg };  // [53] 
 
static csmAction_t  a_stRepeating_0    = { showCharge, "" };
static ActionList_t a_stRepeating      = { 1, { &a_stRepeating_0 } };
static short        n_stRepeating[]    = { 54, 1,54,13,14,21,19,20,15,25,23, 2,54,54,54,22,16,17,54,54,54,54,54,11,54,54,54,54,54,54,54,54,22,24, 3, 8, 4, 7,10, 6,54,54,54,54,54,54,54, 5, 9};
static CState_t     stRepeating        = { 54, "stRepeating", 49, n_stRepeating, &a_stRepeating };  // [54] 
 
static csmAction_t  a_stRecording_0    = { setTimer, "1800000" };
static csmAction_t  a_stRecording_1    = { startRec, "" };
static ActionList_t a_stRecording      = { 2, { &a_stRecording_0, &a_stRecording_1 } };
static short        n_stRecording[]    = { 55, 1,55,55,55,55,55,55,26,27,55, 2,55,55,55,55,55,55,55,55,55,55,55,11,55,55,55,55,55,55,55,55,55,55, 3, 8, 4, 7,10, 6,55,27,55,55,55,55,55, 5, 9};
static CState_t     stRecording        = { 55, "stRecording", 49, n_stRecording, &a_stRecording };  // [55] 
 
static csmAction_t  a_stReviewing_0    = { playRec, "" };
static ActionList_t a_stReviewing      = { 1, { &a_stReviewing_0 } };
static short        n_stReviewing[]    = { 56,29,31,33,34,31,31,31,32,30,31, 2,56,56,56,56,56,56,56,56,56,56,56,11,56,56,56,56,56,56,56,56,31,56, 3, 8, 4, 7,10, 6,56,56,56,56,56,56,56, 5, 9};
static CState_t     stReviewing        = { 56, "stReviewing", 49, n_stReviewing, &a_stReviewing };  // [56] 
 
static csmAction_t  a_stQc1_0          = { filesTest, "" };
static csmAction_t  a_stQc1_1          = { bgLED, "G3_3" };
static ActionList_t a_stQc1            = { 2, { &a_stQc1_0, &a_stQc1_1 } };
static short        n_stQc1[]          = { 57,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,57,57,57,57,57,57,57,57,57,57,57,57,57,57,58,59,57,57};
static CState_t     stQc1              = { 57, "stQc1", 49, n_stQc1, &a_stQc1 };  // [57] 
 
static csmAction_t  a_stQc2_0          = { bgLED, "G3_3" };
static csmAction_t  a_stQc2_1          = { playTune, "C/C/" };
static ActionList_t a_stQc2            = { 2, { &a_stQc2_0, &a_stQc2_1 } };
static short        n_stQc2[]          = { 58,60,60,61,60,60,60,60,60,60,62,60,60,61,60,60,60,60,60,60,62,60,60,60,60,60,60,60,60,60,60,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58};
static CState_t     stQc2              = { 58, "stQc2", 49, n_stQc2, &a_stQc2 };  // [58] 
 
static csmAction_t  a_stQcErrFiles_0   = { writeMsg, "filesTest" };
static csmAction_t  a_stQcErrFiles_1   = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrFiles_2   = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrFiles     = { 3, { &a_stQcErrFiles_0, &a_stQcErrFiles_1, &a_stQcErrFiles_2 } };
static short        n_stQcErrFiles[]   = { 59,42,59,59,59,59,59,59,43,41, 0,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59};
static CState_t     stQcErrFiles       = { 59, "stQcErrFiles", 49, n_stQcErrFiles, &a_stQcErrFiles };  // [59] 
 
static csmAction_t  a_stQcBeep_0       = { playTune, "H_H" };
static csmAction_t  a_stQcBeep_1       = { goPrevSt, "" };
static ActionList_t a_stQcBeep         = { 2, { &a_stQcBeep_0, &a_stQcBeep_1 } };
static short        n_stQcBeep[]       = { 60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60};
static CState_t     stQcBeep           = { 60, "stQcBeep", 49, n_stQcBeep, &a_stQcBeep };  // [60] 
 
static csmAction_t  a_stQc3_0          = { bgLED, "R3_3" };
static csmAction_t  a_stQc3_1          = { playTune, "D/" };
static ActionList_t a_stQc3            = { 2, { &a_stQc3_0, &a_stQc3_1 } };
static short        n_stQc3[]          = { 61,63,60,60,60,60,60,60,60,60,64,63,60,60,60,60,60,60,60,60,64,60,60,60,60,60,60,60,60,60,60,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61};
static CState_t     stQc3              = { 61, "stQc3", 49, n_stQc3, &a_stQc3 };  // [61] 
 
static csmAction_t  a_stQcErrGrn_0     = { writeMsg, "no_Green" };
static csmAction_t  a_stQcErrGrn_1     = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrGrn_2     = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrGrn       = { 3, { &a_stQcErrGrn_0, &a_stQcErrGrn_1, &a_stQcErrGrn_2 } };
static short        n_stQcErrGrn[]     = { 62,42,62,62,62,62,62,62,43,41, 0,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62};
static CState_t     stQcErrGrn         = { 62, "stQcErrGrn", 49, n_stQcErrGrn, &a_stQcErrGrn };  // [62] 
 
static csmAction_t  a_stQc4_0          = { bgLED, "_" };
static csmAction_t  a_stQc4_1          = { LED, "G3" };
static csmAction_t  a_stQc4_2          = { playTune, "E/" };
static ActionList_t a_stQc4            = { 3, { &a_stQc4_0, &a_stQc4_1, &a_stQc4_2 } };
static short        n_stQc4[]          = { 63,60,60,60,65,60,60,60,60,67,66,60,60,60,65,60,60,60,60,67,66,60,60,60,60,60,60,60,60,60,60,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63};
static CState_t     stQc4              = { 63, "stQc4", 49, n_stQc4, &a_stQc4 };  // [63] 
 
static csmAction_t  a_stQcErrRed_0     = { writeMsg, "no_Red" };
static csmAction_t  a_stQcErrRed_1     = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrRed_2     = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrRed       = { 3, { &a_stQcErrRed_0, &a_stQcErrRed_1, &a_stQcErrRed_2 } };
static short        n_stQcErrRed[]     = { 64,42,64,64,64,64,64,64,43,41, 0,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64};
static CState_t     stQcErrRed         = { 64, "stQcErrRed", 49, n_stQcErrRed, &a_stQcErrRed };  // [64] 
 
static csmAction_t  a_stQc5_0          = { startRec, "" };
static csmAction_t  a_stQc5_1          = { setTimer, "4000" };
static ActionList_t a_stQc5            = { 2, { &a_stQc5_0, &a_stQc5_1 } };
static short        n_stQc5[]          = { 65,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,65,65,65,65,65,65,65,65,65,65,68,65,65,65,65,65,65,65};
static CState_t     stQc5              = { 65, "stQc5", 49, n_stQc5, &a_stQc5 };  // [65] 
 
static csmAction_t  a_stQcErrNoMi_0    = { writeMsg, "no_Minus" };
static csmAction_t  a_stQcErrNoMi_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoMi_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoMi      = { 3, { &a_stQcErrNoMi_0, &a_stQcErrNoMi_1, &a_stQcErrNoMi_2 } };
static short        n_stQcErrNoMi[]    = { 66,42,66,66,66,66,66,66,43,41, 0,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66};
static CState_t     stQcErrNoMi        = { 66, "stQcErrNoMi", 49, n_stQcErrNoMi, &a_stQcErrNoMi };  // [66] 
 
static csmAction_t  a_stQcSkip_0       = { playTune, "G/C" };
static ActionList_t a_stQcSkip         = { 1, { &a_stQcSkip_0 } };
static short        n_stQcSkip[]       = { 67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,87,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67};
static CState_t     stQcSkip           = { 67, "stQcSkip", 49, n_stQcSkip, &a_stQcSkip };  // [67] 
 
static csmAction_t  a_stQc6_0          = { finishRec, "" };
static csmAction_t  a_stQc6_1          = { playTune, "F/" };
static ActionList_t a_stQc6            = { 2, { &a_stQc6_0, &a_stQc6_1 } };
static short        n_stQc6[]          = { 68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,69,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68};
static CState_t     stQc6              = { 68, "stQc6", 49, n_stQc6, &a_stQc6 };  // [68] 
 
static ActionList_t a_stQc6b           = {  0,  { 0 } };
static short        n_stQc6b[]         = { 69,69,69,69,69,70,69,69,69,69,71,69,69,69,69,70,69,69,69,69,71,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69};
static CState_t     stQc6b             = { 69, "stQc6b", 49, n_stQc6b, &a_stQc6b };  // [69] 
 
static csmAction_t  a_stQc7_0          = { LED, "G!" };
static csmAction_t  a_stQc7_1          = { playRec, "" };
static ActionList_t a_stQc7            = { 2, { &a_stQc7_0, &a_stQc7_1 } };
static short        n_stQc7[]          = { 70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,72,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70};
static CState_t     stQc7              = { 70, "stQc7", 49, n_stQc7, &a_stQc7 };  // [70] 
 
static csmAction_t  a_stQcErrNoTr_0    = { writeMsg, "no_Tree" };
static csmAction_t  a_stQcErrNoTr_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoTr_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoTr      = { 3, { &a_stQcErrNoTr_0, &a_stQcErrNoTr_1, &a_stQcErrNoTr_2 } };
static short        n_stQcErrNoTr[]    = { 71,42,71,71,71,71,71,71,43,41, 0,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71};
static CState_t     stQcErrNoTr        = { 71, "stQcErrNoTr", 49, n_stQcErrNoTr, &a_stQcErrNoTr };  // [71] 
 
static csmAction_t  a_stQc7b_0         = { LED, "_" };
static csmAction_t  a_stQc7b_1         = { playTune, "G/" };
static ActionList_t a_stQc7b           = { 2, { &a_stQc7b_0, &a_stQc7b_1 } };
static short        n_stQc7b[]         = { 72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,73,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72};
static CState_t     stQc7b             = { 72, "stQc7b", 49, n_stQc7b, &a_stQc7b };  // [72] 
 
static ActionList_t a_stQc8            = {  0,  { 0 } };
static short        n_stQc8[]          = { 73,60,74,60,60,60,60,60,60,60,75,60,74,60,60,60,60,60,60,60,75,60,60,60,60,60,60,60,60,60,60,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73};
static CState_t     stQc8              = { 73, "stQc8", 49, n_stQc8, &a_stQc8 };  // [73] 
 
static csmAction_t  a_stQc9_0          = { LED, "G3" };
static csmAction_t  a_stQc9_1          = { playTune, "A/A/" };
static ActionList_t a_stQc9            = { 2, { &a_stQc9_0, &a_stQc9_1 } };
static short        n_stQc9[]          = { 74,60,60,60,60,60,76,60,60,60,77,60,60,60,60,60,76,60,60,60,77,60,60,60,60,60,60,60,60,60,60,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74};
static CState_t     stQc9              = { 74, "stQc9", 49, n_stQc9, &a_stQc9 };  // [74] 
 
static csmAction_t  a_stQcErrPlay_0    = { writeMsg, "rec_Play" };
static csmAction_t  a_stQcErrPlay_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrPlay_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrPlay      = { 3, { &a_stQcErrPlay_0, &a_stQcErrPlay_1, &a_stQcErrPlay_2 } };
static short        n_stQcErrPlay[]    = { 75,42,75,75,75,75,75,75,43,41, 0,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75};
static CState_t     stQcErrPlay        = { 75, "stQcErrPlay", 49, n_stQcErrPlay, &a_stQcErrPlay };  // [75] 
 
static csmAction_t  a_stQc10_0         = { LED, "G3" };
static csmAction_t  a_stQc10_1         = { playTune, "G/" };
static ActionList_t a_stQc10           = { 2, { &a_stQc10_0, &a_stQc10_1 } };
static short        n_stQc10[]         = { 76,60,60,60,60,60,60,60,78,60,79,60,60,60,60,60,60,60,78,60,79,60,60,60,60,60,60,60,60,60,60,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76};
static CState_t     stQc10             = { 76, "stQc10", 49, n_stQc10, &a_stQc10 };  // [76] 
 
static csmAction_t  a_stQcErrNoLh_0    = { writeMsg, "no_Lhand" };
static csmAction_t  a_stQcErrNoLh_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoLh_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoLh      = { 3, { &a_stQcErrNoLh_0, &a_stQcErrNoLh_1, &a_stQcErrNoLh_2 } };
static short        n_stQcErrNoLh[]    = { 77,42,77,77,77,77,77,77,43,41, 0,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77};
static CState_t     stQcErrNoLh        = { 77, "stQcErrNoLh", 49, n_stQcErrNoLh, &a_stQcErrNoLh };  // [77] 
 
static csmAction_t  a_stQc11_0         = { LED, "G3" };
static csmAction_t  a_stQc11_1         = { playTune, "F/" };
static ActionList_t a_stQc11           = { 2, { &a_stQc11_0, &a_stQc11_1 } };
static short        n_stQc11[]         = { 78,60,60,60,60,60,60,80,60,60,81,60,60,60,60,60,60,80,60,60,81,60,60,60,60,60,60,60,60,60,60,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78};
static CState_t     stQc11             = { 78, "stQc11", 49, n_stQc11, &a_stQc11 };  // [78] 
 
static csmAction_t  a_stQcErrNoPo_0    = { writeMsg, "no_Pot" };
static csmAction_t  a_stQcErrNoPo_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoPo_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoPo      = { 3, { &a_stQcErrNoPo_0, &a_stQcErrNoPo_1, &a_stQcErrNoPo_2 } };
static short        n_stQcErrNoPo[]    = { 79,42,79,79,79,79,79,79,43,41, 0,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79};
static CState_t     stQcErrNoPo        = { 79, "stQcErrNoPo", 49, n_stQcErrNoPo, &a_stQcErrNoPo };  // [79] 
 
static csmAction_t  a_stQc12_0         = { LED, "G3" };
static csmAction_t  a_stQc12_1         = { playTune, "E/" };
static ActionList_t a_stQc12           = { 2, { &a_stQc12_0, &a_stQc12_1 } };
static short        n_stQc12[]         = { 80,60,60,60,60,60,60,60,60,82,83,60,60,60,60,60,60,60,60,82,83,60,60,60,60,60,60,60,60,60,60,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80,80};
static CState_t     stQc12             = { 80, "stQc12", 49, n_stQc12, &a_stQc12 };  // [80] 
 
static csmAction_t  a_stQcErrNoRh_0    = { writeMsg, "no_Rhand" };
static csmAction_t  a_stQcErrNoRh_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoRh_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoRh      = { 3, { &a_stQcErrNoRh_0, &a_stQcErrNoRh_1, &a_stQcErrNoRh_2 } };
static short        n_stQcErrNoRh[]    = { 81,42,81,81,81,81,81,81,43,41, 0,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81,81};
static CState_t     stQcErrNoRh        = { 81, "stQcErrNoRh", 49, n_stQcErrNoRh, &a_stQcErrNoRh };  // [81] 
 
static csmAction_t  a_stQc13_0         = { LED, "G3" };
static csmAction_t  a_stQc13_1         = { playTune, "D/" };
static ActionList_t a_stQc13           = { 2, { &a_stQc13_0, &a_stQc13_1 } };
static short        n_stQc13[]         = { 82,60,60,60,60,60,60,60,60,85,84,60,60,60,60,60,60,60,60,85,84,60,60,60,60,60,60,60,60,60,60,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82,82};
static CState_t     stQc13             = { 82, "stQc13", 49, n_stQc13, &a_stQc13 };  // [82] 
 
static csmAction_t  a_stQcErrNoSt_0    = { writeMsg, "no_Star" };
static csmAction_t  a_stQcErrNoSt_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoSt_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoSt      = { 3, { &a_stQcErrNoSt_0, &a_stQcErrNoSt_1, &a_stQcErrNoSt_2 } };
static short        n_stQcErrNoSt[]    = { 83,42,83,83,83,83,83,83,43,41, 0,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83,83};
static CState_t     stQcErrNoSt        = { 83, "stQcErrNoSt", 49, n_stQcErrNoSt, &a_stQcErrNoSt };  // [83] 
 
static csmAction_t  a_stQc14_0         = { playTune, "C/C*" };
static ActionList_t a_stQc14           = { 1, { &a_stQc14_0 } };
static short        n_stQc14[]         = { 84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,86,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84,84};
static CState_t     stQc14             = { 84, "stQc14", 49, n_stQc14, &a_stQc14 };  // [84] 
 
static csmAction_t  a_stQcErrNoTa_0    = { writeMsg, "no_Table" };
static csmAction_t  a_stQcErrNoTa_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoTa_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoTa      = { 3, { &a_stQcErrNoTa_0, &a_stQcErrNoTa_1, &a_stQcErrNoTa_2 } };
static short        n_stQcErrNoTa[]    = { 85,42,85,85,85,85,85,85,43,41, 0,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85};
static CState_t     stQcErrNoTa        = { 85, "stQcErrNoTa", 49, n_stQcErrNoTa, &a_stQcErrNoTa };  // [85] 
 
static csmAction_t  a_stQc15_0         = { writeMsg, "QC_OK" };
static csmAction_t  a_stQc15_1         = { bgLED, "G2_8" };
static ActionList_t a_stQc15           = { 2, { &a_stQc15_0, &a_stQc15_1 } };
static short        n_stQc15[]         = { 86,42,86,86,86,86,86,86,43,41, 0,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86,86};
static CState_t     stQc15             = { 86, "stQc15", 49, n_stQc15, &a_stQc15 };  // [86] 
 
static csmAction_t  a_stQcSkip2_0      = { writeMsg, "QC_OK_short" };
static csmAction_t  a_stQcSkip2_1      = { bgLED, "G2_8" };
static ActionList_t a_stQcSkip2        = { 2, { &a_stQcSkip2_0, &a_stQcSkip2_1 } };
static short        n_stQcSkip2[]      = { 87,42,87,87,87,87,87,87,43,41, 0,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87,87};
static CState_t     stQcSkip2          = { 87, "stQcSkip2", 49, n_stQcSkip2, &a_stQcSkip2 };  // [87] 
 
static CSList_t  preCSlist = {  88, 
  {
          &stQcTest,          &stWakeup,         &stGoSleep,          &stSleepy,      &stOnCharging,
    &stOnCharging75,     &stNearCharged,       &stOnCharged,       &stOnLowBatt,     &stNotCharging,
       &stOnBattMin,         &stUSBmode,        &stCloseUSB,      &stPlayLouder,      &stPlaySofter,
       &stPlayPause,    &stPlayJumpBack,     &stPlayJumpFwd,      &stPlayResume,      &stOnPrevSubj,
      &stOnNextSubj,       &stOnNextMsg,     &stOnRepeatMsg,       &stOnPrevMsg,            &stWait,
  &stBeginRecording, &stRecordingPaused,   &stRecordingDone,&stRecordingResumed,&stEndRecordingHome,
   &stRecordAnother,    &stEndRecording,    &stReviewPaused,    &stReviewLouder,    &stReviewSofter,
   &stReviewResumed,      &stIdleLouder,      &stIdleSofter,        &stShowBatt,          &stChgPkg,
          &stNxtPkg,           &stQcUSB,        &stQcReboot,       &stQcSysTest,       &stWelcoming,
      &stPromptSubj,    &stPromptingSub,        &stUnSleepy,      &stFallAsleep,      &stAnnouncing,
      &stInvitation,  &stPromptNextSubj,         &stPlaying,        &stInterMsg,       &stRepeating,
       &stRecording,       &stReviewing,             &stQc1,             &stQc2,      &stQcErrFiles,
          &stQcBeep,             &stQc3,        &stQcErrGrn,             &stQc4,        &stQcErrRed,
             &stQc5,       &stQcErrNoMi,          &stQcSkip,             &stQc6,            &stQc6b,
             &stQc7,       &stQcErrNoTr,            &stQc7b,             &stQc8,             &stQc9,
       &stQcErrPlay,            &stQc10,       &stQcErrNoLh,            &stQc11,       &stQcErrNoPo,
            &stQc12,       &stQcErrNoRh,            &stQc13,       &stQcErrNoSt,            &stQc14,
       &stQcErrNoTa,            &stQc15,         &stQcSkip2,
  }
};  
static CSM_t preCSM = { 
    "// TB CSM 2022-04-27: V20 One touch recording", 
    &preTB_Config, preSysAudio, &preCSlist
};  // preCSM
 
void     preloadCSM( void ){
    CSM = &preCSM;
    TB_Config = &preTB_Config;
}  // preloadCSM()
 
// preloadCSM.c 
