// preloaded TBook Control State Machine   preloadCSM.c
// generated by org.amplio.CSMcompile version: 8(2021-10-15)
// run at 2022-03-09 13:37:01
// from C:\Users\geneb\Documents\CSMcompile\data\control_def.txt of: 2022-03-07 13:50:22
#include "packageData.h" 
//Ver:   // TB CSM 2022-03-07: V18 fix-- state name mismatch for BattMin
static TBConfig_t  preTB_Config = { 
  6,  // default_volume 
  60000,  // powerCheckMS
  5000,  // shortIdleMS 
  20000,  // longIdleMS 
  50,  // minShortPressMS 
  1000,  // minLongPressMS 
  0, // qcTestState 
  1, // initState 
  "system/audio/",  // systemAudio 
  "_49G",  // bgPulse 
  "G!",  // fgPlaying 
  "G2_3!",  // fgPlayPaused 
  "R!",  // fgRecording 
  "R2_3!",  // fgRecordPaused 
  "O!",  // fgSavingRec 
  "G3_3G3",  // fgSaveRec 
  "R3_3R3",  // fgCancelRec 
  "O5o5!",  // fgUSB_MSC 
  "R8_2R8_2R8_20!",  // fgTB_Error 
  "_3R3_3R3_3R3_5!",  // fgNoUSBcable 
  "G5g5!",  // fgUSBconnect 
  "G_3G_3G_9G_3G_9G_3",  // fgPowerDown 
};  // preTB_Config
 
static AudioList_t preSysAudio[] = { 
7,  // # PlaySys prompts used by CSM 
{ 
"welcome",
"rh_for_subj",
"rh_for_nxt_subj",
"cir_record_ideas",
"rh_things_to_do",
"louder",
"softer",
} 
};  // preSysAudio 
 
static csmAction_t  a_stQcTest_0       = { playTune, "C/" };
static ActionList_t a_stQcTest         = { 1, { &a_stQcTest_0 } };
static short        n_stQcTest[]       = {  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
static CState_t     stQcTest           = { 0, "stQcTest", 47, n_stQcTest, &a_stQcTest };  // [0] 
 
static csmAction_t  a_stWakeup_0       = { LED, "_" };
static csmAction_t  a_stWakeup_1       = { bgLED, "bgPulse" };
static csmAction_t  a_stWakeup_2       = { changePkg, "" };
static csmAction_t  a_stWakeup_3       = { playSys, "welcome" };
static ActionList_t a_stWakeup         = { 4, { &a_stWakeup_0, &a_stWakeup_1, &a_stWakeup_2, &a_stWakeup_3 } };
static short        n_stWakeup[]       = {  1, 1, 1,10,11,18,16,17,12, 1,20, 2, 1, 1, 1, 1,13,14, 1, 1, 1, 1,22, 1, 1,19, 1, 1, 1, 1, 1,39,21,21, 3, 4, 5, 6, 7, 8, 1, 1, 1, 1, 1, 1, 1};
static CState_t     stWakeup           = { 1, "stWakeup", 47, n_stWakeup, &a_stWakeup };  // [1] 
 
static csmAction_t  a_stGoSleep_0      = { bgLED, "R_3" };
static csmAction_t  a_stGoSleep_1      = { setTimer, "1000" };
static ActionList_t a_stGoSleep        = { 2, { &a_stGoSleep_0, &a_stGoSleep_1 } };
static short        n_stGoSleep[]      = {  2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,43, 2, 2, 2, 2, 2};
static CState_t     stGoSleep          = { 2, "stGoSleep", 47, n_stGoSleep, &a_stGoSleep };  // [2] 
 
static csmAction_t  a_stSleepy_0       = { bgLED, "O_9" };
static csmAction_t  a_stSleepy_1       = { saveSt, "1" };
static csmAction_t  a_stSleepy_2       = { setTimer, "5000" };
static ActionList_t a_stSleepy         = { 3, { &a_stSleepy_0, &a_stSleepy_1, &a_stSleepy_2 } };
static short        n_stSleepy[]       = {  3, 1,42,42,42,42,42,42,42,42,42, 2,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42, 3, 3, 3, 3, 4, 5, 6, 7, 8, 3, 2, 3, 3, 3, 3, 3};
static CState_t     stSleepy           = { 3, "stSleepy", 47, n_stSleepy, &a_stSleepy };  // [3] 
 
static csmAction_t  a_stOnLowBatt_0    = { bgLED, "R3_2" };
static csmAction_t  a_stOnLowBatt_1    = { goPrevSt, "" };
static ActionList_t a_stOnLowBatt      = { 2, { &a_stOnLowBatt_0, &a_stOnLowBatt_1 } };
static short        n_stOnLowBatt[]    = {  4, 1, 4,31,32,18,16,17, 4, 4,20, 2,34, 4, 4, 4, 4, 4, 4, 4, 4, 4,35,30,33,19, 4, 4, 4, 4, 4, 4,21,21, 3, 4, 5, 6, 7, 8, 4, 4, 4, 4, 4, 4, 4};
static CState_t     stOnLowBatt        = { 4, "stOnLowBatt", 47, n_stOnLowBatt, &a_stOnLowBatt };  // [4] 
 
static csmAction_t  a_stOnCharging_0   = { bgLED, "R_19" };
static csmAction_t  a_stOnCharging_1   = { goPrevSt, "" };
static ActionList_t a_stOnCharging     = { 2, { &a_stOnCharging_0, &a_stOnCharging_1 } };
static short        n_stOnCharging[]   = {  5, 1, 5,31,32, 5, 5, 5, 5, 5, 5, 2,34, 5, 5, 5, 5, 5, 5, 5, 5, 5,35,30,33, 5, 5, 5, 5, 5, 5, 5, 5, 5, 3, 4, 5, 6, 7, 8, 5, 5, 5, 5, 5, 5, 5};
static CState_t     stOnCharging       = { 5, "stOnCharging", 47, n_stOnCharging, &a_stOnCharging };  // [5] 
 
static csmAction_t  a_stOnCharged_0    = { bgLED, "G" };
static csmAction_t  a_stOnCharged_1    = { goPrevSt, "" };
static ActionList_t a_stOnCharged      = { 2, { &a_stOnCharged_0, &a_stOnCharged_1 } };
static short        n_stOnCharged[]    = {  6, 1, 6,31,32, 6, 6, 6, 6, 6, 6, 2,34, 6, 6, 6, 6, 6, 6, 6, 6, 6,35,30,33, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 4, 5, 6, 7, 8, 6, 6, 6, 6, 6, 6, 6};
static CState_t     stOnCharged        = { 6, "stOnCharged", 47, n_stOnCharged, &a_stOnCharged };  // [6] 
 
static csmAction_t  a_stOnBattMin_0    = { bgLED, "R5_5" };
static csmAction_t  a_stOnBattMin_1    = { setTimer, "5000" };
static ActionList_t a_stOnBattMin      = { 2, { &a_stOnBattMin_0, &a_stOnBattMin_1 } };
static short        n_stOnBattMin[]    = {  7, 1, 1, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,43, 7, 7, 7, 7, 7};
static CState_t     stOnBattMin        = { 7, "stOnBattMin", 47, n_stOnBattMin, &a_stOnBattMin };  // [7] 
 
static csmAction_t  a_stNearCharged_0  = { bgLED, "R_9" };
static csmAction_t  a_stNearCharged_1  = { goPrevSt, "" };
static ActionList_t a_stNearCharged    = { 2, { &a_stNearCharged_0, &a_stNearCharged_1 } };
static short        n_stNearCharged[]  = {  8, 1, 8,31,32, 8, 8, 8, 8, 8, 8, 2,34, 8, 8, 8, 8, 8, 8, 8, 8, 8,35,30,33, 8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 4, 5, 6, 7, 8, 8, 8, 8, 8, 8, 8, 8};
static CState_t     stNearCharged      = { 8, "stNearCharged", 47, n_stNearCharged, &a_stNearCharged };  // [8] 
 
static csmAction_t  a_stCloseUSB_0     = { endUSB, "" };
static csmAction_t  a_stCloseUSB_1     = { bgLED, "G_29" };
static csmAction_t  a_stCloseUSB_2     = { setTimer, "1000" };
static ActionList_t a_stCloseUSB       = { 3, { &a_stCloseUSB_0, &a_stCloseUSB_1, &a_stCloseUSB_2 } };
static short        n_stCloseUSB[]     = {  9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 1, 9, 9, 9, 9, 9};
static CState_t     stCloseUSB         = { 9, "stCloseUSB", 47, n_stCloseUSB, &a_stCloseUSB };  // [9] 
 
static csmAction_t  a_stPlayLouder_0   = { volAdj, "1" };
static csmAction_t  a_stPlayLouder_1   = { goPrevSt, "" };
static ActionList_t a_stPlayLouder     = { 2, { &a_stPlayLouder_0, &a_stPlayLouder_1 } };
static short        n_stPlayLouder[]   = { 10, 1,10,10,11,10,10,10,12,10,10, 2,10,10,10,10,13,14,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10, 3, 4, 5, 6, 7, 8,10,10,10,10,10,10,10};
static CState_t     stPlayLouder       = { 10, "stPlayLouder", 47, n_stPlayLouder, &a_stPlayLouder };  // [10] 
 
static csmAction_t  a_stPlaySofter_0   = { volAdj, "-1" };
static csmAction_t  a_stPlaySofter_1   = { goPrevSt, "" };
static ActionList_t a_stPlaySofter     = { 2, { &a_stPlaySofter_0, &a_stPlaySofter_1 } };
static short        n_stPlaySofter[]   = { 11, 1,11,10,11,11,11,11,12,11,11, 2,11,11,11,11,13,14,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11, 3, 4, 5, 6, 7, 8,11,11,11,11,11,11,11};
static CState_t     stPlaySofter       = { 11, "stPlaySofter", 47, n_stPlaySofter, &a_stPlaySofter };  // [11] 
 
static csmAction_t  a_stPlayPause_0    = { saveSt, "2" };
static csmAction_t  a_stPlayPause_1    = { setTimer, "8000" };
static csmAction_t  a_stPlayPause_2    = { pausePlay, "" };
static ActionList_t a_stPlayPause      = { 3, { &a_stPlayPause_0, &a_stPlayPause_1, &a_stPlayPause_2 } };
static short        n_stPlayPause[]    = { 12, 1,12,10,11,18,16,17,15,12,20, 2,12,12,12,12,13,14,12,12,12,12,22,12,12,19,12,12,12,12,12,12,21,21, 3, 4, 5, 6, 7, 8,12, 2,12,12,12,12,12};
static CState_t     stPlayPause        = { 12, "stPlayPause", 47, n_stPlayPause, &a_stPlayPause };  // [12] 
 
static csmAction_t  a_stPlayJumpBack_0 = { posAdj, "-7" };
static ActionList_t a_stPlayJumpBack   = { 1, { &a_stPlayJumpBack_0 } };
static short        n_stPlayJumpBack[] = { 13, 1,13,10,11,18,16,17,12,13,20, 2,13,13,13,13,13,14,13,13,13,13,22,13,13,19,13,13,13,13,13,13,21,21, 3, 4, 5, 6, 7, 8,13,13,13,13,13,13,13};
static CState_t     stPlayJumpBack     = { 13, "stPlayJumpBack", 47, n_stPlayJumpBack, &a_stPlayJumpBack };  // [13] 
 
static csmAction_t  a_stPlayJumpFwd_0  = { posAdj, "60" };
static ActionList_t a_stPlayJumpFwd    = { 1, { &a_stPlayJumpFwd_0 } };
static short        n_stPlayJumpFwd[]  = { 14, 1,14,10,11,18,16,17,12,14,20, 2,14,14,14,14,13,14,14,14,14,14,22,14,14,19,14,14,14,14,14,14,21,21, 3, 4, 5, 6, 7, 8,14,14,14,14,14,14,14};
static CState_t     stPlayJumpFwd      = { 14, "stPlayJumpFwd", 47, n_stPlayJumpFwd, &a_stPlayJumpFwd };  // [14] 
 
static csmAction_t  a_stPlayResume_0   = { resumePlay, "" };
static csmAction_t  a_stPlayResume_1   = { goSavedSt, "2" };
static ActionList_t a_stPlayResume     = { 2, { &a_stPlayResume_0, &a_stPlayResume_1 } };
static short        n_stPlayResume[]   = { 15, 1,15,10,11,18,16,17,12,15,20, 2,15,15,15,15,13,14,15,15,15,15,22,15,15,19,15,15,15,15,15,15,21,21, 3, 4, 5, 6, 7, 8,15,15,15,15,15,15,15};
static CState_t     stPlayResume       = { 15, "stPlayResume", 47, n_stPlayResume, &a_stPlayResume };  // [15] 
 
static csmAction_t  a_stOnPrevSubj_0   = { subjAdj, "-1" };
static csmAction_t  a_stOnPrevSubj_1   = { playSubj, "nm" };
static ActionList_t a_stOnPrevSubj     = { 2, { &a_stOnPrevSubj_0, &a_stOnPrevSubj_1 } };
static short        n_stOnPrevSubj[]   = { 16, 1,16,10,11,18,16,17,12,16,20, 2,16,16,16,16,13,14,16,16,16,16,22,16,16,19,16,16,16,16,16,44,21,21, 3, 4, 5, 6, 7, 8,16,16,16,16,16,16,16};
static CState_t     stOnPrevSubj       = { 16, "stOnPrevSubj", 47, n_stOnPrevSubj, &a_stOnPrevSubj };  // [16] 
 
static csmAction_t  a_stOnNextSubj_0   = { subjAdj, "1" };
static csmAction_t  a_stOnNextSubj_1   = { playSubj, "nm" };
static ActionList_t a_stOnNextSubj     = { 2, { &a_stOnNextSubj_0, &a_stOnNextSubj_1 } };
static short        n_stOnNextSubj[]   = { 17, 1,17,10,11,18,16,17,12,17,20, 2,17,17,17,17,13,14,17,17,17,17,22,17,17,19,17,17,17,17,17,44,21,21, 3, 4, 5, 6, 7, 8,17,17,17,17,17,17,17};
static CState_t     stOnNextSubj       = { 17, "stOnNextSubj", 47, n_stOnNextSubj, &a_stOnNextSubj };  // [17] 
 
static csmAction_t  a_stOnNextMsg_0    = { msgAdj, "1" };
static csmAction_t  a_stOnNextMsg_1    = { playSubj, "msg" };
static ActionList_t a_stOnNextMsg      = { 2, { &a_stOnNextMsg_0, &a_stOnNextMsg_1 } };
static short        n_stOnNextMsg[]    = { 18, 1,18,10,11,18,16,17,12,18,20, 2,18,18,18,18,13,14,18,18,18,18,22,18,18,19,18,18,18,18,18,47,21,21, 3, 4, 5, 6, 7, 8,18,18,18,18,18,18,18};
static CState_t     stOnNextMsg        = { 18, "stOnNextMsg", 47, n_stOnNextMsg, &a_stOnNextMsg };  // [18] 
 
static csmAction_t  a_stOnRepeatMsg_0  = { msgAdj, "1" };
static csmAction_t  a_stOnRepeatMsg_1  = { playSubj, "msg" };
static ActionList_t a_stOnRepeatMsg    = { 2, { &a_stOnRepeatMsg_0, &a_stOnRepeatMsg_1 } };
static short        n_stOnRepeatMsg[]  = { 19, 1,19,10,11,18,16,17,12,19,20, 2,19,19,19,19,13,14,19,19,19,19,22,19,19,19,19,19,19,19,19,48,21,21, 3, 4, 5, 6, 7, 8,19,19,19,19,19,19,19};
static CState_t     stOnRepeatMsg      = { 19, "stOnRepeatMsg", 47, n_stOnRepeatMsg, &a_stOnRepeatMsg };  // [19] 
 
static csmAction_t  a_stOnPrevMsg_0    = { msgAdj, "-1" };
static csmAction_t  a_stOnPrevMsg_1    = { playSubj, "msg" };
static ActionList_t a_stOnPrevMsg      = { 2, { &a_stOnPrevMsg_0, &a_stOnPrevMsg_1 } };
static short        n_stOnPrevMsg[]    = { 20, 1,20,10,11,18,16,17,12,20,20, 2,20,20,20,20,13,14,20,20,20,20,22,20,20,19,20,20,20,20,20,47,21,21, 3, 4, 5, 6, 7, 8,20,20,20,20,20,20,20};
static CState_t     stOnPrevMsg        = { 20, "stOnPrevMsg", 47, n_stOnPrevMsg, &a_stOnPrevMsg };  // [20] 
 
static ActionList_t a_stWait           = {  0,  { 0 } };
static short        n_stWait[]         = { 21, 1,21,31,32,18,16,17,21,21,20, 2,34,21,21,21,21,21,21,21,21,21,35,30,33,19,21,21,21,21,21,21,21,21, 3, 4, 5, 6, 7, 8,21,21,21,21,21,21,21};
static CState_t     stWait             = { 21, "stWait", 47, n_stWait, &a_stWait };  // [21] 
 
static csmAction_t  a_stOnFeedback_0   = { playSys, "cir_record_ideas" };
static ActionList_t a_stOnFeedback     = { 1, { &a_stOnFeedback_0 } };
static short        n_stOnFeedback[]   = { 22, 1,24,22,22,22,22,22,22,23,22, 2,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22, 3, 4, 5, 6, 7, 8,22,22,22,22,22,22,22};
static CState_t     stOnFeedback       = { 22, "stOnFeedback", 47, n_stOnFeedback, &a_stOnFeedback };  // [22] 
 
static csmAction_t  a_stFbOptions_0    = { playSys, "rh_things_to_do" };
static ActionList_t a_stFbOptions      = { 1, { &a_stFbOptions_0 } };
static short        n_stFbOptions[]    = { 23, 1,23,23,23,23,23,23,23,23,23, 2,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23,23, 3, 4, 5, 6, 7, 8,23,23,23,23,23,23,23};
static CState_t     stFbOptions        = { 23, "stFbOptions", 47, n_stFbOptions, &a_stFbOptions };  // [23] 
 
static csmAction_t  a_stStartRec_0     = { startRec, "" };
static ActionList_t a_stStartRec       = { 1, { &a_stStartRec_0 } };
static short        n_stStartRec[]     = { 24, 1,26,24,24,27,24,24,25,29,28, 2,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24,24, 3, 4, 5, 6, 7, 8,24,24,24,24,24,24,24};
static CState_t     stStartRec         = { 24, "stStartRec", 47, n_stStartRec, &a_stStartRec };  // [24] 
 
static csmAction_t  a_stPauseRec_0     = { saveSt, "2" };
static csmAction_t  a_stPauseRec_1     = { pauseRec, "" };
static ActionList_t a_stPauseRec       = { 2, { &a_stPauseRec_0, &a_stPauseRec_1 } };
static short        n_stPauseRec[]     = { 25, 1,26,25,25,27,25,25,25,29,28, 2,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25,25, 3, 4, 5, 6, 7, 8,25,25,25,25,25,25,25};
static CState_t     stPauseRec         = { 25, "stPauseRec", 47, n_stPauseRec, &a_stPauseRec };  // [25] 
 
static csmAction_t  a_stFinishRec_0    = { finishRec, "" };
static ActionList_t a_stFinishRec      = { 1, { &a_stFinishRec_0 } };
static short        n_stFinishRec[]    = { 26, 1,26,26,26,27,26,26,25,29,28, 2,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26,26, 3, 4, 5, 6, 7, 8,26,26,26,26,26,26,26};
static CState_t     stFinishRec        = { 26, "stFinishRec", 47, n_stFinishRec, &a_stFinishRec };  // [26] 
 
static csmAction_t  a_stPlayRec_0      = { playRec, "" };
static ActionList_t a_stPlayRec        = { 1, { &a_stPlayRec_0 } };
static short        n_stPlayRec[]      = { 27, 1,26,27,27,27,27,27,25,29,28, 2,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27,27, 3, 4, 5, 6, 7, 8,27,27,27,27,27,27,27};
static CState_t     stPlayRec          = { 27, "stPlayRec", 47, n_stPlayRec, &a_stPlayRec };  // [27] 
 
static csmAction_t  a_stCancelRec_0    = { saveRec, "del" };
static ActionList_t a_stCancelRec      = { 1, { &a_stCancelRec_0 } };
static short        n_stCancelRec[]    = { 28, 1,28,28,28,18,16,17,28,28,20, 2,28,28,28,28,28,28,28,28,28,28,22,28,28,19,28,28,28,28,28,28,21,21, 3, 4, 5, 6, 7, 8,28,28,28,28,28,28,28};
static CState_t     stCancelRec        = { 28, "stCancelRec", 47, n_stCancelRec, &a_stCancelRec };  // [28] 
 
static csmAction_t  a_stSaveRec_0      = { saveRec, "sv" };
static ActionList_t a_stSaveRec        = { 1, { &a_stSaveRec_0 } };
static short        n_stSaveRec[]      = { 29, 1,29,29,29,18,16,17,29,29,20, 2,29,29,29,29,29,29,29,29,29,29,22,29,29,19,29,29,29,29,29,29,21,21, 3, 4, 5, 6, 7, 8,29,29,29,29,29,29,29};
static CState_t     stSaveRec          = { 29, "stSaveRec", 47, n_stSaveRec, &a_stSaveRec };  // [29] 
 
static csmAction_t  a_stUSBmode_0      = { bgLED, "O2_8" };
static csmAction_t  a_stUSBmode_1      = { startUSB, "" };
static ActionList_t a_stUSBmode        = { 2, { &a_stUSBmode_0, &a_stUSBmode_1 } };
static short        n_stUSBmode[]      = { 30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30, 9,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30};
static CState_t     stUSBmode          = { 30, "stUSBmode", 47, n_stUSBmode, &a_stUSBmode };  // [30] 
 
static csmAction_t  a_stIdleLouder_0   = { volAdj, "1" };
static csmAction_t  a_stIdleLouder_1   = { playSys, "louder" };
static csmAction_t  a_stIdleLouder_2   = { goPrevSt, "" };
static ActionList_t a_stIdleLouder     = { 3, { &a_stIdleLouder_0, &a_stIdleLouder_1, &a_stIdleLouder_2 } };
static short        n_stIdleLouder[]   = { 31, 1,31,10,11,31,31,31,12,31,31, 2,31,31,31,31,13,14,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31,31, 3, 4, 5, 6, 7, 8,31,31,31,31,31,31,31};
static CState_t     stIdleLouder       = { 31, "stIdleLouder", 47, n_stIdleLouder, &a_stIdleLouder };  // [31] 
 
static csmAction_t  a_stIdleSofter_0   = { volAdj, "-1" };
static csmAction_t  a_stIdleSofter_1   = { playSys, "softer" };
static csmAction_t  a_stIdleSofter_2   = { goPrevSt, "" };
static ActionList_t a_stIdleSofter     = { 3, { &a_stIdleSofter_0, &a_stIdleSofter_1, &a_stIdleSofter_2 } };
static short        n_stIdleSofter[]   = { 32, 1,32,10,11,32,32,32,12,32,32, 2,32,32,32,32,13,14,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32, 3, 4, 5, 6, 7, 8,32,32,32,32,32,32,32};
static CState_t     stIdleSofter       = { 32, "stIdleSofter", 47, n_stIdleSofter, &a_stIdleSofter };  // [32] 
 
static csmAction_t  a_stShowBatt_0     = { showCharge, "" };
static csmAction_t  a_stShowBatt_1     = { goPrevSt, "" };
static ActionList_t a_stShowBatt       = { 2, { &a_stShowBatt_0, &a_stShowBatt_1 } };
static short        n_stShowBatt[]     = { 33, 1,33,31,32,33,33,33,33,33,33, 2,34,33,33,33,33,33,33,33,33,33,35,30,33,33,33,33,33,33,33,33,33,33, 3, 4, 5, 6, 7, 8,33,33,33,33,33,33,33};
static CState_t     stShowBatt         = { 33, "stShowBatt", 47, n_stShowBatt, &a_stShowBatt };  // [33] 
 
static csmAction_t  a_stChgPkg_0       = { changePkg, "" };
static ActionList_t a_stChgPkg         = { 1, { &a_stChgPkg_0 } };
static short        n_stChgPkg[]       = { 34, 1,34,31,32,18,16,17,34,34,20, 2,34,34,34,34,34,34,34,34,34,34,22,30,33,19,34,34,34,34,34,34,21,21, 3, 4, 5, 6, 7, 8,34,34,34,34,34,34,34};
static CState_t     stChgPkg           = { 34, "stChgPkg", 47, n_stChgPkg, &a_stChgPkg };  // [34] 
 
static csmAction_t  a_stNxtPkg_0       = { playNxtPkg, "" };
static ActionList_t a_stNxtPkg         = { 1, { &a_stNxtPkg_0 } };
static short        n_stNxtPkg[]       = { 35, 1,35,31,32,35,35,35,35,35,35, 2,34,35,35,35,35,35,35,35,35,35,35,30,33,35,35,35,35,35,35,35,35,35, 3, 4, 5, 6, 7, 8,35,35,35,35,35,35,35};
static CState_t     stNxtPkg           = { 35, "stNxtPkg", 47, n_stNxtPkg, &a_stNxtPkg };  // [35] 
 
static csmAction_t  a_stQcUSB_0        = { bgLED, "O2_8" };
static csmAction_t  a_stQcUSB_1        = { startUSB, "" };
static ActionList_t a_stQcUSB          = { 2, { &a_stQcUSB_0, &a_stQcUSB_1 } };
static short        n_stQcUSB[]        = { 36,37,36,36,36,36,36,36,38,36, 0,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36,36};
static CState_t     stQcUSB            = { 36, "stQcUSB", 47, n_stQcUSB, &a_stQcUSB };  // [36] 
 
static csmAction_t  a_stQcReboot_0     = { sysBoot, "" };
static ActionList_t a_stQcReboot       = { 1, { &a_stQcReboot_0 } };
static short        n_stQcReboot[]     = { 37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37,37};
static CState_t     stQcReboot         = { 37, "stQcReboot", 47, n_stQcReboot, &a_stQcReboot };  // [37] 
 
static csmAction_t  a_stQcSysTest_0    = { playTune, "CG/.FDEH.G/" };
static ActionList_t a_stQcSysTest      = { 1, { &a_stQcSysTest_0 } };
static short        n_stQcSysTest[]    = { 38,37,38,38,38,38,38,38,38,36, 0,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38,38};
static CState_t     stQcSysTest        = { 38, "stQcSysTest", 47, n_stQcSysTest, &a_stQcSysTest };  // [38] 
 
static ActionList_t a_stWelcoming      = {  0,  { 0 } };
static short        n_stWelcoming[]    = { 39, 1,39,10,11,18,16,17,12,39,20, 2,39,39,39,39,13,14,39,39,39,39,22,39,39,19,39,39,39,39,39,39,40,21, 3, 4, 5, 6, 7, 8,39,39,39,39,39,39,39};
static CState_t     stWelcoming        = { 39, "stWelcoming", 47, n_stWelcoming, &a_stWelcoming };  // [39] 
 
static csmAction_t  a_stPromptSubj_0   = { playSys, "rh_for_subj" };
static ActionList_t a_stPromptSubj     = { 1, { &a_stPromptSubj_0 } };
static short        n_stPromptSubj[]   = { 40, 1,40,10,11,18,16,17,12,40,20, 2,40,40,40,40,13,14,40,40,40,40,22,40,40,19,40,40,40,40,40,41,21,21, 3, 4, 5, 6, 7, 8,40,40,40,40,40,40,40};
static CState_t     stPromptSubj       = { 40, "stPromptSubj", 47, n_stPromptSubj, &a_stPromptSubj };  // [40] 
 
static ActionList_t a_stPromptingSub   = {  0,  { 0 } };
static short        n_stPromptingSub[] = { 41, 1,41,10,11,18,16,17,12,41,20, 2,41,41,41,41,13,14,41,41,41,41,22,41,41,19,41,41,41,41,41,41,21,21, 3, 4, 5, 6, 7, 8,41,41,41,41,41,41,41};
static CState_t     stPromptingSub     = { 41, "stPromptingSub", 47, n_stPromptingSub, &a_stPromptingSub };  // [41] 
 
static csmAction_t  a_stUnSleepy_0     = { bgLED, "bgPulse" };
static csmAction_t  a_stUnSleepy_1     = { goSavedSt, "1" };
static ActionList_t a_stUnSleepy       = { 2, { &a_stUnSleepy_0, &a_stUnSleepy_1 } };
static short        n_stUnSleepy[]     = { 42, 1,42,42,42,42,42,42,42,42,42, 2,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42, 3, 4, 5, 6, 7, 8,42,42,42,42,42,42,42};
static CState_t     stUnSleepy         = { 42, "stUnSleepy", 47, n_stUnSleepy, &a_stUnSleepy };  // [42] 
 
static csmAction_t  a_stFallAsleep_0   = { powerDown, "" };
static ActionList_t a_stFallAsleep     = { 1, { &a_stFallAsleep_0 } };
static short        n_stFallAsleep[]   = { 43, 1, 1,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43,43};
static CState_t     stFallAsleep       = { 43, "stFallAsleep", 47, n_stFallAsleep, &a_stFallAsleep };  // [43] 
 
static ActionList_t a_stAnnouncing     = {  0,  { 0 } };
static short        n_stAnnouncing[]   = { 44, 1,44,10,11,18,16,17,12,44,20, 2,44,44,44,44,13,14,44,44,44,44,22,44,44,19,44,44,44,44,44,44,45,21, 3, 4, 5, 6, 7, 8,44,44,44,44,44,44,44};
static CState_t     stAnnouncing       = { 44, "stAnnouncing", 47, n_stAnnouncing, &a_stAnnouncing };  // [44] 
 
static csmAction_t  a_stInvitation_0   = { playSubj, "pr" };
static ActionList_t a_stInvitation     = { 1, { &a_stInvitation_0 } };
static short        n_stInvitation[]   = { 45, 1,45,10,11,18,16,17,12,45,20, 2,45,45,45,45,13,14,45,45,45,45,22,45,45,19,45,45,45,45,45,45,46,21, 3, 4, 5, 6, 7, 8,45,45,45,45,45,45,45};
static CState_t     stInvitation       = { 45, "stInvitation", 47, n_stInvitation, &a_stInvitation };  // [45] 
 
static csmAction_t  a_stPromptNextSubj_0 = { playSys, "rh_for_nxt_subj" };
static ActionList_t a_stPromptNextSubj = { 1, { &a_stPromptNextSubj_0 } };
static short        n_stPromptNextSubj[] = { 46, 1,46,10,11,18,16,17,12,46,20, 2,46,46,46,46,13,14,46,46,46,46,22,46,46,19,46,46,46,46,46,46,21,21, 3, 4, 5, 6, 7, 8,46,46,46,46,46,46,46};
static CState_t     stPromptNextSubj   = { 46, "stPromptNextSubj", 47, n_stPromptNextSubj, &a_stPromptNextSubj };  // [46] 
 
static ActionList_t a_stPlaying        = {  0,  { 0 } };
static short        n_stPlaying[]      = { 47, 1,47,10,11,18,16,17,12,47,20, 2,47,47,47,47,13,14,47,47,47,47,22,47,47,19,47,47,47,47,47,47,21,21, 3, 4, 5, 6, 7, 8,47,47,47,47,47,47,47};
static CState_t     stPlaying          = { 47, "stPlaying", 47, n_stPlaying, &a_stPlaying };  // [47] 
 
static ActionList_t a_stRepeating      = {  0,  { 0 } };
static short        n_stRepeating[]    = { 48, 1,48,10,11,18,16,17,12,48,20, 2,48,48,48,48,13,14,48,48,48,48,22,48,48,19,48,48,48,48,48,48,19,21, 3, 4, 5, 6, 7, 8,48,48,48,48,48,48,48};
static CState_t     stRepeating        = { 48, "stRepeating", 47, n_stRepeating, &a_stRepeating };  // [48] 
 
static csmAction_t  a_stQc1_0          = { filesTest, "" };
static csmAction_t  a_stQc1_1          = { bgLED, "G3_3" };
static ActionList_t a_stQc1            = { 2, { &a_stQc1_0, &a_stQc1_1 } };
static short        n_stQc1[]          = { 49,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,49,49,49,49,49,49,49,49,49,49,49,49,49,49,50,51};
static CState_t     stQc1              = { 49, "stQc1", 47, n_stQc1, &a_stQc1 };  // [49] 
 
static csmAction_t  a_stQc2_0          = { bgLED, "G3_3" };
static csmAction_t  a_stQc2_1          = { playTune, "C/C/" };
static ActionList_t a_stQc2            = { 2, { &a_stQc2_0, &a_stQc2_1 } };
static short        n_stQc2[]          = { 50,52,52,53,52,52,52,52,52,52,54,52,52,53,52,52,52,52,52,52,54,52,52,52,52,52,52,52,52,52,52,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50,50};
static CState_t     stQc2              = { 50, "stQc2", 47, n_stQc2, &a_stQc2 };  // [50] 
 
static csmAction_t  a_stQcErrFiles_0   = { writeMsg, "filesTest" };
static csmAction_t  a_stQcErrFiles_1   = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrFiles_2   = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrFiles     = { 3, { &a_stQcErrFiles_0, &a_stQcErrFiles_1, &a_stQcErrFiles_2 } };
static short        n_stQcErrFiles[]   = { 51,37,51,51,51,51,51,51,38,36, 0,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51,51};
static CState_t     stQcErrFiles       = { 51, "stQcErrFiles", 47, n_stQcErrFiles, &a_stQcErrFiles };  // [51] 
 
static csmAction_t  a_stQcBeep_0       = { playTune, "H_H" };
static csmAction_t  a_stQcBeep_1       = { goPrevSt, "" };
static ActionList_t a_stQcBeep         = { 2, { &a_stQcBeep_0, &a_stQcBeep_1 } };
static short        n_stQcBeep[]       = { 52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52,52};
static CState_t     stQcBeep           = { 52, "stQcBeep", 47, n_stQcBeep, &a_stQcBeep };  // [52] 
 
static csmAction_t  a_stQc3_0          = { bgLED, "R3_3" };
static csmAction_t  a_stQc3_1          = { playTune, "D/" };
static ActionList_t a_stQc3            = { 2, { &a_stQc3_0, &a_stQc3_1 } };
static short        n_stQc3[]          = { 53,55,52,52,52,52,52,52,52,52,56,55,52,52,52,52,52,52,52,52,56,52,52,52,52,52,52,52,52,52,52,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53,53};
static CState_t     stQc3              = { 53, "stQc3", 47, n_stQc3, &a_stQc3 };  // [53] 
 
static csmAction_t  a_stQcErrGrn_0     = { writeMsg, "no_Green" };
static csmAction_t  a_stQcErrGrn_1     = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrGrn_2     = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrGrn       = { 3, { &a_stQcErrGrn_0, &a_stQcErrGrn_1, &a_stQcErrGrn_2 } };
static short        n_stQcErrGrn[]     = { 54,37,54,54,54,54,54,54,38,36, 0,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54,54};
static CState_t     stQcErrGrn         = { 54, "stQcErrGrn", 47, n_stQcErrGrn, &a_stQcErrGrn };  // [54] 
 
static csmAction_t  a_stQc4_0          = { bgLED, "_" };
static csmAction_t  a_stQc4_1          = { LED, "G3" };
static csmAction_t  a_stQc4_2          = { playTune, "E/" };
static ActionList_t a_stQc4            = { 3, { &a_stQc4_0, &a_stQc4_1, &a_stQc4_2 } };
static short        n_stQc4[]          = { 55,52,52,52,57,52,52,52,52,59,58,52,52,52,57,52,52,52,52,59,58,52,52,52,52,52,52,52,52,52,52,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55,55};
static CState_t     stQc4              = { 55, "stQc4", 47, n_stQc4, &a_stQc4 };  // [55] 
 
static csmAction_t  a_stQcErrRed_0     = { writeMsg, "no_Red" };
static csmAction_t  a_stQcErrRed_1     = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrRed_2     = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrRed       = { 3, { &a_stQcErrRed_0, &a_stQcErrRed_1, &a_stQcErrRed_2 } };
static short        n_stQcErrRed[]     = { 56,37,56,56,56,56,56,56,38,36, 0,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56,56};
static CState_t     stQcErrRed         = { 56, "stQcErrRed", 47, n_stQcErrRed, &a_stQcErrRed };  // [56] 
 
static csmAction_t  a_stQc5_0          = { startRec, "" };
static csmAction_t  a_stQc5_1          = { setTimer, "4000" };
static ActionList_t a_stQc5            = { 2, { &a_stQc5_0, &a_stQc5_1 } };
static short        n_stQc5[]          = { 57,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,57,57,57,57,57,57,57,57,57,57,60,57,57,57,57,57};
static CState_t     stQc5              = { 57, "stQc5", 47, n_stQc5, &a_stQc5 };  // [57] 
 
static csmAction_t  a_stQcErrNoMi_0    = { writeMsg, "no_Minus" };
static csmAction_t  a_stQcErrNoMi_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoMi_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoMi      = { 3, { &a_stQcErrNoMi_0, &a_stQcErrNoMi_1, &a_stQcErrNoMi_2 } };
static short        n_stQcErrNoMi[]    = { 58,37,58,58,58,58,58,58,38,36, 0,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58,58};
static CState_t     stQcErrNoMi        = { 58, "stQcErrNoMi", 47, n_stQcErrNoMi, &a_stQcErrNoMi };  // [58] 
 
static csmAction_t  a_stQcSkip_0       = { playTune, "G/C" };
static ActionList_t a_stQcSkip         = { 1, { &a_stQcSkip_0 } };
static short        n_stQcSkip[]       = { 59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,59,79,59,59,59,59,59,59,59,59,59,59,59,59,59,59};
static CState_t     stQcSkip           = { 59, "stQcSkip", 47, n_stQcSkip, &a_stQcSkip };  // [59] 
 
static csmAction_t  a_stQc6_0          = { finishRec, "" };
static csmAction_t  a_stQc6_1          = { playTune, "F/" };
static ActionList_t a_stQc6            = { 2, { &a_stQc6_0, &a_stQc6_1 } };
static short        n_stQc6[]          = { 60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,60,61,60,60,60,60,60,60,60,60,60,60,60,60,60,60};
static CState_t     stQc6              = { 60, "stQc6", 47, n_stQc6, &a_stQc6 };  // [60] 
 
static ActionList_t a_stQc6b           = {  0,  { 0 } };
static short        n_stQc6b[]         = { 61,61,61,61,61,62,61,61,61,61,63,61,61,61,61,62,61,61,61,61,63,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61};
static CState_t     stQc6b             = { 61, "stQc6b", 47, n_stQc6b, &a_stQc6b };  // [61] 
 
static csmAction_t  a_stQc7_0          = { LED, "G!" };
static csmAction_t  a_stQc7_1          = { playRec, "" };
static ActionList_t a_stQc7            = { 2, { &a_stQc7_0, &a_stQc7_1 } };
static short        n_stQc7[]          = { 62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,62,64,62,62,62,62,62,62,62,62,62,62,62,62,62,62};
static CState_t     stQc7              = { 62, "stQc7", 47, n_stQc7, &a_stQc7 };  // [62] 
 
static csmAction_t  a_stQcErrNoTr_0    = { writeMsg, "no_Tree" };
static csmAction_t  a_stQcErrNoTr_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoTr_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoTr      = { 3, { &a_stQcErrNoTr_0, &a_stQcErrNoTr_1, &a_stQcErrNoTr_2 } };
static short        n_stQcErrNoTr[]    = { 63,37,63,63,63,63,63,63,38,36, 0,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63,63};
static CState_t     stQcErrNoTr        = { 63, "stQcErrNoTr", 47, n_stQcErrNoTr, &a_stQcErrNoTr };  // [63] 
 
static csmAction_t  a_stQc7b_0         = { LED, "_" };
static csmAction_t  a_stQc7b_1         = { playTune, "G/" };
static ActionList_t a_stQc7b           = { 2, { &a_stQc7b_0, &a_stQc7b_1 } };
static short        n_stQc7b[]         = { 64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,65,64,64,64,64,64,64,64,64,64,64,64,64,64,64};
static CState_t     stQc7b             = { 64, "stQc7b", 47, n_stQc7b, &a_stQc7b };  // [64] 
 
static ActionList_t a_stQc8            = {  0,  { 0 } };
static short        n_stQc8[]          = { 65,52,66,52,52,52,52,52,52,52,67,52,66,52,52,52,52,52,52,52,67,52,52,52,52,52,52,52,52,52,52,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65,65};
static CState_t     stQc8              = { 65, "stQc8", 47, n_stQc8, &a_stQc8 };  // [65] 
 
static csmAction_t  a_stQc9_0          = { LED, "G3" };
static csmAction_t  a_stQc9_1          = { playTune, "A/A/" };
static ActionList_t a_stQc9            = { 2, { &a_stQc9_0, &a_stQc9_1 } };
static short        n_stQc9[]          = { 66,52,52,52,52,52,68,52,52,52,69,52,52,52,52,52,68,52,52,52,69,52,52,52,52,52,52,52,52,52,52,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66};
static CState_t     stQc9              = { 66, "stQc9", 47, n_stQc9, &a_stQc9 };  // [66] 
 
static csmAction_t  a_stQcErrPlay_0    = { writeMsg, "rec_Play" };
static csmAction_t  a_stQcErrPlay_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrPlay_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrPlay      = { 3, { &a_stQcErrPlay_0, &a_stQcErrPlay_1, &a_stQcErrPlay_2 } };
static short        n_stQcErrPlay[]    = { 67,37,67,67,67,67,67,67,38,36, 0,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67,67};
static CState_t     stQcErrPlay        = { 67, "stQcErrPlay", 47, n_stQcErrPlay, &a_stQcErrPlay };  // [67] 
 
static csmAction_t  a_stQc10_0         = { LED, "G3" };
static csmAction_t  a_stQc10_1         = { playTune, "G/" };
static ActionList_t a_stQc10           = { 2, { &a_stQc10_0, &a_stQc10_1 } };
static short        n_stQc10[]         = { 68,52,52,52,52,52,52,52,70,52,71,52,52,52,52,52,52,52,70,52,71,52,52,52,52,52,52,52,52,52,52,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68,68};
static CState_t     stQc10             = { 68, "stQc10", 47, n_stQc10, &a_stQc10 };  // [68] 
 
static csmAction_t  a_stQcErrNoLh_0    = { writeMsg, "no_Lhand" };
static csmAction_t  a_stQcErrNoLh_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoLh_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoLh      = { 3, { &a_stQcErrNoLh_0, &a_stQcErrNoLh_1, &a_stQcErrNoLh_2 } };
static short        n_stQcErrNoLh[]    = { 69,37,69,69,69,69,69,69,38,36, 0,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69,69};
static CState_t     stQcErrNoLh        = { 69, "stQcErrNoLh", 47, n_stQcErrNoLh, &a_stQcErrNoLh };  // [69] 
 
static csmAction_t  a_stQc11_0         = { LED, "G3" };
static csmAction_t  a_stQc11_1         = { playTune, "F/" };
static ActionList_t a_stQc11           = { 2, { &a_stQc11_0, &a_stQc11_1 } };
static short        n_stQc11[]         = { 70,52,52,52,52,52,52,72,52,52,73,52,52,52,52,52,52,72,52,52,73,52,52,52,52,52,52,52,52,52,52,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70,70};
static CState_t     stQc11             = { 70, "stQc11", 47, n_stQc11, &a_stQc11 };  // [70] 
 
static csmAction_t  a_stQcErrNoPo_0    = { writeMsg, "no_Pot" };
static csmAction_t  a_stQcErrNoPo_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoPo_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoPo      = { 3, { &a_stQcErrNoPo_0, &a_stQcErrNoPo_1, &a_stQcErrNoPo_2 } };
static short        n_stQcErrNoPo[]    = { 71,37,71,71,71,71,71,71,38,36, 0,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71,71};
static CState_t     stQcErrNoPo        = { 71, "stQcErrNoPo", 47, n_stQcErrNoPo, &a_stQcErrNoPo };  // [71] 
 
static csmAction_t  a_stQc12_0         = { LED, "G3" };
static csmAction_t  a_stQc12_1         = { playTune, "E/" };
static ActionList_t a_stQc12           = { 2, { &a_stQc12_0, &a_stQc12_1 } };
static short        n_stQc12[]         = { 72,52,52,52,52,52,52,52,52,74,75,52,52,52,52,52,52,52,52,74,75,52,52,52,52,52,52,52,52,52,52,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72,72};
static CState_t     stQc12             = { 72, "stQc12", 47, n_stQc12, &a_stQc12 };  // [72] 
 
static csmAction_t  a_stQcErrNoRh_0    = { writeMsg, "no_Rhand" };
static csmAction_t  a_stQcErrNoRh_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoRh_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoRh      = { 3, { &a_stQcErrNoRh_0, &a_stQcErrNoRh_1, &a_stQcErrNoRh_2 } };
static short        n_stQcErrNoRh[]    = { 73,37,73,73,73,73,73,73,38,36, 0,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73,73};
static CState_t     stQcErrNoRh        = { 73, "stQcErrNoRh", 47, n_stQcErrNoRh, &a_stQcErrNoRh };  // [73] 
 
static csmAction_t  a_stQc13_0         = { LED, "G3" };
static csmAction_t  a_stQc13_1         = { playTune, "D/" };
static ActionList_t a_stQc13           = { 2, { &a_stQc13_0, &a_stQc13_1 } };
static short        n_stQc13[]         = { 74,52,52,52,52,52,52,52,52,77,76,52,52,52,52,52,52,52,52,77,76,52,52,52,52,52,52,52,52,52,52,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74,74};
static CState_t     stQc13             = { 74, "stQc13", 47, n_stQc13, &a_stQc13 };  // [74] 
 
static csmAction_t  a_stQcErrNoSt_0    = { writeMsg, "no_Star" };
static csmAction_t  a_stQcErrNoSt_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoSt_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoSt      = { 3, { &a_stQcErrNoSt_0, &a_stQcErrNoSt_1, &a_stQcErrNoSt_2 } };
static short        n_stQcErrNoSt[]    = { 75,37,75,75,75,75,75,75,38,36, 0,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75,75};
static CState_t     stQcErrNoSt        = { 75, "stQcErrNoSt", 47, n_stQcErrNoSt, &a_stQcErrNoSt };  // [75] 
 
static csmAction_t  a_stQc14_0         = { playTune, "C/C*" };
static ActionList_t a_stQc14           = { 1, { &a_stQc14_0 } };
static short        n_stQc14[]         = { 76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,76,78,76,76,76,76,76,76,76,76,76,76,76,76,76,76};
static CState_t     stQc14             = { 76, "stQc14", 47, n_stQc14, &a_stQc14 };  // [76] 
 
static csmAction_t  a_stQcErrNoTa_0    = { writeMsg, "no_Table" };
static csmAction_t  a_stQcErrNoTa_1    = { bgLED, "R9_6" };
static csmAction_t  a_stQcErrNoTa_2    = { playTune, "H.*_H.*_H.*_H.*_" };
static ActionList_t a_stQcErrNoTa      = { 3, { &a_stQcErrNoTa_0, &a_stQcErrNoTa_1, &a_stQcErrNoTa_2 } };
static short        n_stQcErrNoTa[]    = { 77,37,77,77,77,77,77,77,38,36, 0,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77,77};
static CState_t     stQcErrNoTa        = { 77, "stQcErrNoTa", 47, n_stQcErrNoTa, &a_stQcErrNoTa };  // [77] 
 
static csmAction_t  a_stQc15_0         = { writeMsg, "QC_OK" };
static csmAction_t  a_stQc15_1         = { bgLED, "G2_8" };
static ActionList_t a_stQc15           = { 2, { &a_stQc15_0, &a_stQc15_1 } };
static short        n_stQc15[]         = { 78,37,78,78,78,78,78,78,38,36, 0,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78,78};
static CState_t     stQc15             = { 78, "stQc15", 47, n_stQc15, &a_stQc15 };  // [78] 
 
static csmAction_t  a_stQcSkip2_0      = { writeMsg, "QC_OK_short" };
static csmAction_t  a_stQcSkip2_1      = { bgLED, "G2_8" };
static ActionList_t a_stQcSkip2        = { 2, { &a_stQcSkip2_0, &a_stQcSkip2_1 } };
static short        n_stQcSkip2[]      = { 79,37,79,79,79,79,79,79,38,36, 0,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79};
static CState_t     stQcSkip2          = { 79, "stQcSkip2", 47, n_stQcSkip2, &a_stQcSkip2 };  // [79] 
 
static CSList_t  preCSlist = {  80, 
  {
          &stQcTest,          &stWakeup,         &stGoSleep,          &stSleepy,       &stOnLowBatt,
      &stOnCharging,       &stOnCharged,       &stOnBattMin,     &stNearCharged,        &stCloseUSB,
      &stPlayLouder,      &stPlaySofter,       &stPlayPause,    &stPlayJumpBack,     &stPlayJumpFwd,
      &stPlayResume,      &stOnPrevSubj,      &stOnNextSubj,       &stOnNextMsg,     &stOnRepeatMsg,
       &stOnPrevMsg,            &stWait,      &stOnFeedback,       &stFbOptions,        &stStartRec,
        &stPauseRec,       &stFinishRec,         &stPlayRec,       &stCancelRec,         &stSaveRec,
         &stUSBmode,      &stIdleLouder,      &stIdleSofter,        &stShowBatt,          &stChgPkg,
          &stNxtPkg,           &stQcUSB,        &stQcReboot,       &stQcSysTest,       &stWelcoming,
      &stPromptSubj,    &stPromptingSub,        &stUnSleepy,      &stFallAsleep,      &stAnnouncing,
      &stInvitation,  &stPromptNextSubj,         &stPlaying,       &stRepeating,             &stQc1,
             &stQc2,      &stQcErrFiles,          &stQcBeep,             &stQc3,        &stQcErrGrn,
             &stQc4,        &stQcErrRed,             &stQc5,       &stQcErrNoMi,          &stQcSkip,
             &stQc6,            &stQc6b,             &stQc7,       &stQcErrNoTr,            &stQc7b,
             &stQc8,             &stQc9,       &stQcErrPlay,            &stQc10,       &stQcErrNoLh,
            &stQc11,       &stQcErrNoPo,            &stQc12,       &stQcErrNoRh,            &stQc13,
       &stQcErrNoSt,            &stQc14,       &stQcErrNoTa,            &stQc15,         &stQcSkip2,

  }
};  
static CSM_t preCSM = { 
    "// TB CSM 2022-03-07: V18 fix-- state name mismatch for BattMin", 
    &preTB_Config, preSysAudio, &preCSlist
};  // preCSM
 
void     preloadCSM( void ){
    CSM = &preCSM;
    TB_Config = &preTB_Config;
}  // preloadCSM()
 
// preloadCSM.c 
